"""Export service: ZIP stem pack, DAW-ready folders, REAPER .rpp (Phase 2)."""

from __future__ import annotations

import io
import json
import zipfile
from pathlib import Path

from app.models.project import ExportRecord, ProjectManifest


README_TEMPLATE = """\
STEM EXPORT PACKAGE
===================
Generated by Stem Extraction + DAW Export System

Project : {title}
BPM     : {bpm}
Key     : {key}
Duration: {duration:.1f} seconds
Stems   : {stem_list}

IMPORT INSTRUCTIONS
-------------------

ABLETON LIVE
  1. Open Ableton Live.
  2. Drag each WAV stem from this folder directly into the Arrangement view.
  3. All stems start at bar 1, beat 1 (0:00).
  4. Set project BPM to {bpm} in the tempo control.
  5. (Optional) Enable Warp on each clip and set BPM to {bpm}.

FL STUDIO
  1. Open FL Studio.
  2. Go to the Mixer and import each stem as an audio clip.
  3. Set the project tempo to {bpm}.

LOGIC PRO / GARAGEBAND
  1. Create a new Empty Project.
  2. Set the project tempo to {bpm}.
  3. File > Import > Audio File — import each stem.
  4. Drag each clip to bar 1 on separate tracks.

REAPER
  1. Open REAPER.
  2. Drag all WAV files into the REAPER timeline.
  3. All stems will auto-align at the start.
  4. Set the project BPM to {bpm} in Project Settings.

PRO TOOLS
  1. Create a new session at 44100 Hz / 24-bit.
  2. Import audio (Ctrl+Shift+I) — select all WAV stems.
  3. Choose "Clip by Clip" placement at the session start.

UNIVERSAL RULE
  All stems start at exactly 0.0 seconds and have the same length.
  They will align perfectly in any DAW at the same tempo.

INCLUDED FILES
--------------
{file_list}

manifest.json contains the full project metadata including beat grid,
tempo map, key, LUFS measurements, and stem confidence scores.
"""


def build_wav_zip(
    project_dir: Path,
    manifest: ProjectManifest,
    include_stems: list[str] | None = None,
    include_midi: bool = False,
    include_manifest: bool = True,
    include_readme: bool = True,
) -> tuple[Path, ExportRecord]:
    """
    Package stems + manifest into a ZIP file.
    Returns (zip_path, ExportRecord).
    """
    exports_dir = project_dir / "exports"
    exports_dir.mkdir(exist_ok=True)
    zip_path = exports_dir / "stems_pack.zip"

    active_stems = [
        s for s in manifest.stems
        if include_stems is None or s.name in include_stems
    ]

    file_lines = []
    stem_names = []
    for s in active_stems:
        stem_names.append(s.label)
        file_lines.append(f"  {s.name}.wav   ({s.label})")
        if include_midi and s.midi_file:
            file_lines.append(f"  midi/{s.name}.mid   (MIDI — {s.label})")
    if include_manifest:
        file_lines.append("  manifest.json")
    if include_readme:
        file_lines.append("  README_IMPORT.txt")

    readme_text = README_TEMPLATE.format(
        title=manifest.title,
        bpm=manifest.analysis.bpm or "Unknown",
        key=manifest.analysis.key or "Unknown",
        duration=manifest.source.duration_seconds if manifest.source else 0,
        stem_list=", ".join(stem_names) or "none",
        file_list="\n".join(file_lines),
    )

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        # Add stems
        for s in active_stems:
            stem_file = project_dir / s.file
            if stem_file.exists():
                zf.write(stem_file, arcname=f"{s.name}.wav")

        # Add MIDI sidecars
        if include_midi:
            for s in active_stems:
                if s.midi_file:
                    midi_file = project_dir / s.midi_file
                    if midi_file.exists():
                        zf.write(midi_file, arcname=f"midi/{s.name}.mid")

        # Add manifest
        if include_manifest:
            manifest_json = manifest.model_dump_json(indent=2)
            zf.writestr("manifest.json", manifest_json)

        # Add readme
        if include_readme:
            zf.writestr("README_IMPORT.txt", readme_text)

    size_bytes = zip_path.stat().st_size

    record = ExportRecord(
        type="wav_zip",
        file=f"exports/stems_pack.zip",
        includes_midi=include_midi,
        includes_manifest=include_manifest,
        size_bytes=size_bytes,
    )
    return zip_path, record


def build_reaper_rpp(
    project_dir: Path,
    manifest: ProjectManifest,
) -> tuple[Path, ExportRecord]:
    """
    Generate a REAPER .rpp project file with all stems placed at bar 1.
    Phase 2 feature.
    """
    exports_dir = project_dir / "exports"
    exports_dir.mkdir(exist_ok=True)

    bpm = manifest.analysis.bpm or 120.0
    title = manifest.title
    sample_rate = manifest.source.sample_rate if manifest.source else 44100

    tracks = ""
    for idx, stem in enumerate(manifest.stems):
        stem_file_abs = str((project_dir / stem.file).resolve())
        vol = _db_to_linear(stem.volume_db)
        pan = stem.pan
        mute = 1 if stem.is_muted else 0
        track_color = _stem_color(stem.name)

        tracks += f"""  <TRACK
    NAME "{stem.label}"
    PEAKCOL {track_color}
    BEAT -1
    AUTOMODE 0
    VOLPAN {vol:.6f} {pan:.6f} -1 -1 1
    MUTE {mute}
    SOLO 0
    <ITEM
      POSITION 0
      SNAPOFFS 0
      LENGTH {stem.duration_seconds:.6f}
      LOOP 0
      ALLTAKES 0
      MUTE 0
      SEL 1
      IGUID {{00000000-0000-0000-0000-{idx:012d}}}
      IID {idx + 1}
      NAME "{stem.name}"
      VOLPAN 1.000000 0.000000 1.000000 -1
      SOFFS 0
      PLAYRATE 1 0 0 -1 0 0.0025
      CHANMODE 0
      <SOURCE WAVE
        FILE "{stem_file_abs}"
      >
    >
  >
"""

    rpp_content = f"""<REAPER_PROJECT 0.1 "6.0/linux64" 1719600000
  TEMPO {bpm:.4f} 4 4
  SAMPLERATE {sample_rate} 0 0
  PANLAW 1
  ITEMBUF 8
  DEFPITCHMODE 589824 0
  TAKELANE 1
  RIPPLE 0
  GROUPOVERRIDE 0 0 0
  AUTOXFADE 129
  ENVATTRIB 1
  OVERLAPS 1
  LOOPTM 0 0
  POOL_LINKED 0
  POOLEDENVATTRIB 0
  TIMEBASE 0
  SAMPLEBIAS 0
  RENDER_FILE ""
  RENDER_PATTERN ""
  RENDER_FMT 0 2 0
  RENDER_1X 0
  RENDER_RANGE 1 0 0 18 1000
  RENDER_RESAMPLE 3 0 1
  RENDER_ADDTOPROJ 0
  RENDER_STEMS 0
  RENDER_DITHER 0
  RENDER_NORMALIZE 0 0
  TIMELOCKMODE 1
  TEMPOENVLOCKMODE 1
  ITEMMIX 1
  DEFCCS 1
  TAKELANE 1
  SAMPLERATE {sample_rate} 0 0
{tracks}>
"""

    rpp_path = exports_dir / f"{_safe_filename(title)}.rpp"
    rpp_path.write_text(rpp_content)

    size_bytes = rpp_path.stat().st_size
    record = ExportRecord(
        type="reaper_rpp",
        file=f"exports/{rpp_path.name}",
        includes_midi=False,
        includes_manifest=False,
        size_bytes=size_bytes,
    )
    return rpp_path, record


def _db_to_linear(db: float) -> float:
    import math
    return round(10 ** (db / 20), 6)


def _stem_color(name: str) -> int:
    colors = {
        "vocals": 33554432,
        "drums": 16777216,
        "bass": 8388608,
        "guitar": 4194304,
        "piano": 2097152,
        "other": 1048576,
    }
    return colors.get(name, 0)


def _safe_filename(name: str) -> str:
    return "".join(c if c.isalnum() or c in "-_ " else "_" for c in name).strip()
