export const dnaFields = [
  ["soundIdentity", "Sound identity", "What should remain recognizable across your work?"],
  ["genres", "Genres and influences", "Describe the elements you value rather than copying an artist."],
  ["vocalChain", "Vocal-chain philosophy", "What do you preserve, correct, and emphasize?"],
  ["drums", "Drum selection", "Describe impact, groove, density, and kick/bass relationships."],
  ["melody", "Melody preferences", "Register, harmony, repetition, and space for the voice."],
  ["mixBalance", "Mix balance", "Where should the lead, drums, bass, and ambience sit?"],
  ["emotion", "Emotional direction", "What should the listener feel?"],
  ["arrangement", "Arrangement", "How do you build contrast, escalation, and transitions?"],
  ["coaching", "Artist coaching", "How do you direct takes and challenge weak sections?"],
  ["release", "Release beliefs", "What earns a release and what must be ready first?"],
  ["branding", "Branding principles", "How do sound, visuals, and audience connect?"],
  ["workflow", "Studio workflow", "Preparation, recording, review, versioning, and delivery."],
  ["rules", "Creative rules", "Include the reason and exceptions for each rule."],
  ["avoid", "Things to avoid", "Sounds, habits, language, and processing you reject."],
  ["signature", "Signature moves", "Repeatable techniques and when they work."]
] as const;
export type DnaKey = typeof dnaFields[number][0];
export type ProducerDna = Record<DnaKey, string>;
export const emptyDna = Object.fromEntries(dnaFields.map(([key]) => [key, ""])) as ProducerDna;
export const starterDna: ProducerDna = { ...emptyDna,
  soundIdentity: "Aggressive rap, Southern energy, sharp writing, confident baritone delivery, strong hooks.",
  genres: "Southern rap and trap; Caribbean and reggaetón rhythmic influence where the song calls for it.",
  vocalChain: "Preserve useful baritone weight and intelligibility. Judge the recording before adding processing. Compare at matched loudness.",
  drums: "Impact and interesting pockets with enough space for fast flows and breath placement.",
  arrangement: "Every section should develop the story. Use flow switches and authored transitions; remove repetition that does not escalate.",
  coaching: "Direct, practical feedback. Preserve approved material; identify the weakest section and test alternatives.",
  release: "Tease, introduce, build curiosity, release, amplify, extend. Prepare assets and rights before delivery.",
  branding: "Premium editorial imagery; sound and visuals share one recognizable world.",
  rules: "Prioritize quotable bars, memorable hooks, performance potential, replay value, and room for vocals.",
  avoid: "Forced slang, filler, generic praise, derivative imitation, celebrity-name presets, fake scarcity, and guaranteed success claims."
};
export interface KnowledgeCard { id: string; topic: string; title: string; guidance: string; next: string; source?: { label: string; url: string }; jurisdiction?: string; }
export const knowledge: KnowledgeCard[] = [
  { id:"record", topic:"Recording", title:"Start with the recording", guidance:"Confirm input routing, microphone technique, room sound, and clean recording level before processing. A preset cannot reliably restore a clipped take.", next:"Record a dry test phrase, then compare it with every effect bypassed." },
  { id:"vocal", topic:"Vocal production", title:"Build a chain around delivery", guidance:"Choose processing for the actual take and its role: lead, hook, double, background, or ad-lib. Preserve intentional character and compare at matched loudness.", next:"Describe your voice, delivery, desired tone, and current effects." },
  { id:"mix", topic:"Mixing", title:"Balance before complexity", guidance:"Check arrangement and level balance before adding more effects. Mud, harshness, or weak presence are listening hypotheses until measured or auditioned.", next:"Mark the timestamps where the problem appears and compare dry versus processed." },
  { id:"master", topic:"Mastering", title:"Prepare an approved mix", guidance:"Mastering is final tonal/dynamic and delivery work. Fix arrangement, distortion, and vocal balance in the mix first. Do not use one universal loudness target for every release.", next:"Confirm the destination and export requirements with the receiving engineer or distributor." },
  { id:"song", topic:"Songwriting", title:"Write for the performance", guidance:"Evaluate meaning, cadence, breaths, rhyme, contrast, and delivery. Preserve approved copy when requested. Text alone does not establish melodic or vocal performance quality.", next:"Share the section and identify the line or moment that must land." },
  { id:"beat", topic:"Beat selection", title:"Audition the voice against the beat", guidance:"Compare candidates against the same concept and vocal phrase. Assess energy, register, density, hook space, and performance fit separately from personal enjoyment.", next:"Choose up to three beats and audition the same vocal idea over each." },
  { id:"brand", topic:"Artist branding", title:"Make the music and image agree", guidance:"Define audience, emotional world, differentiators, visual references, and recurring content pillars. Avoid inventing a biography or changing an approved identity.", next:"Write one audience promise and collect three references with reasons." },
  { id:"distribution", topic:"Distribution", title:"Prepare delivery early", guidance:"Distribution requirements and delivery lead times vary. Verify the selected distributor's current policy instead of assuming a universal deadline or format.", next:"Choose the distributor and confirm its artwork, audio, metadata, and scheduling requirements." },
  { id:"publishing", topic:"Publishing and royalties", title:"Separate the song from the recording", guidance:"Map songwriter, publisher, recording-artist, producer, and master-owner roles independently. Collection routes depend on territory and agreements.", next:"List your country, roles, distributor, administrator, and existing registrations.", jurisdiction:"Territory dependent", source:{label:"U.S. Copyright Office",url:"https://www.copyright.gov/music-modernization/"} },
  { id:"pro", topic:"PROs", title:"Composition performance royalties", guidance:"A PRO such as ASCAP handles composition public-performance royalties. It is not a replacement for every other collection route. Check the current organization guidance for your territory.", next:"Confirm writer/publisher details and work registrations with your PRO.", jurisdiction:"United States example", source:{label:"ASCAP",url:"https://www.ascap.com/music-creators"} },
  { id:"mechanical", topic:"Royalties", title:"Digital mechanical collection", guidance:"The MLC administers eligible U.S. digital audio mechanical royalties. Its role is distinct from recording royalties and PRO collection; confirm eligibility and administration before registering.", next:"Check whether your publisher or administrator already manages your relevant share.", jurisdiction:"United States", source:{label:"The MLC",url:"https://www.themlc.com/"} },
  { id:"recording-royalty", topic:"Royalties", title:"Sound-recording performance collection", guidance:"SoundExchange administers U.S. statutory noninteractive digital sound-recording performance royalties. This is distinct from composition collection.", next:"Confirm artist and rights-owner registration requirements with SoundExchange.", jurisdiction:"United States", source:{label:"SoundExchange",url:"https://www.soundexchange.com/what-we-do/for-artists-labels-and-producers/"} },
  { id:"sync", topic:"Sync licensing", title:"Build a rights-ready pitch", guidance:"Track composition and master ownership, contacts, clearance status, alternate versions, and usage scope. An upload or attached license does not itself establish clearance.", next:"Prepare an ownership/contact sheet and instrumental/clean alternatives when authorized." },
  { id:"metadata", topic:"Metadata", title:"Keep one authoritative credit record", guidance:"Keep artist spelling, titles, contributor roles, explicit status, identifiers, and ownership consistent across versions and delivery records.", next:"Review the project's Release Center and confirm all contributors." },
  { id:"rollout", topic:"Release rollouts", title:"Work backward from release", guidance:"Build tease, introduction, curiosity, release, amplification, and extension tasks around actual capacity. Rights and delivery blockers should be resolved before promotional commitments.", next:"Set the date, identify missing assets, and assign one owner to each task." },
  { id:"content", topic:"Content strategy", title:"Build a content ecosystem", guidance:"Develop hook clips, performance moments, context, lyrics, artwork, and post-release material around one recognizable world. Publishing remains a user-approved action.", next:"Plan three repeatable formats that you can produce consistently." },
  { id:"fans", topic:"Fanbase growth", title:"Measure meaningful audience actions", guidance:"Track returning listeners, saves, direct audience sign-ups, ticket or product purchases, and engagement quality. Do not promise streams or placements.", next:"Choose one audience and one conversion goal for the next campaign." },
  { id:"studio", topic:"Studio business", title:"Define the service before booking", guidance:"State deliverables, file limits, revision rounds, turnaround, payment terms, and responsibilities. Separate recording, mixing, mastering, and coaching scope.", next:"Prepare a service brief with the work, deadline, and files required." },
  { id:"agreements", topic:"Producer agreements", title:"Track terms and evidence", guidance:"Record fees, master participation, publishing, license scope, credits, delivery, and approvals separately. Drafting assistance is not a determination of legal enforceability.", next:"List unresolved terms and have the final agreement reviewed in the relevant jurisdiction." },
  { id:"splits", topic:"Collaboration splits", title:"Confirm shares with collaborators", guidance:"Keep composition and master shares separate. A total of 100% is a math check, not proof that collaborators agreed. Preserve written confirmation.", next:"Review names, roles, identifiers, shares, and approval status." },
  { id:"funnels", topic:"Marketing funnels", title:"Connect discovery to a next action", guidance:"Define discovery content, an artist destination, and one conversion action. Compare spend with meaningful outcomes rather than vanity metrics.", next:"Map a clip to a song page and an optional fan sign-up." },
  { id:"live", topic:"Live performance", title:"Rehearse the real set", guidance:"Prepare approved backing tracks, transitions, cues, breath plans, technical requirements, and recovery options. Test the actual playback chain.", next:"Run the complete set without stopping and note weak transitions." },
  { id:"money", topic:"Artist monetization", title:"Match offers to demand", guidance:"Evaluate music, shows, merchandise, direct support, licensing, and services using costs, rights, capacity, and audience interest. Forecasts are estimates.", next:"Cost one offer and test demand before committing to inventory." },
  { id:"development", topic:"Platform development", title:"Turn an idea into a specification", guidance:"Describe the trigger, current behavior, desired behavior, data, permissions, error states, and acceptance checks. Chat can draft implementation work; it cannot execute repository changes or deployments from this interface.", next:"Name the feature and give a concrete before-and-after example." }
];
export interface ToolConcept { id:string; name:string; purpose:string; audience:string; problem:string; features:string[]; workflow:string; ui:string; ai:string; presets:string[]; mvp:string; advanced:string; lesson:string; prompt:string; }
export const toolConcepts: ToolConcept[] = [
  {id:"vocal-chain",name:"DNA Vocal Chain",purpose:"Shape a vocal chain around your method.",audience:"Home-recording rappers and singers",problem:"Stacking effects without a clear chain philosophy",features:["Input checks","Corrective EQ","Dynamics","De-essing","Space","Level-matched A/B"],workflow:"Describe the dry take → choose intent → review chain → audition in your DAW",ui:"Input meter, ordered chain, four macro controls, explanation panel",ai:"Explain a proposed chain and its tradeoffs; no cloud processing in playback",presets:["Baritone Forward","Dry Southern Lead","Wide Hook"],mvp:"Working browser processor at /tm-vocal: EQ, compression, saturation, reverb, delay, short-delay widening, peak containment, device presets and WAV export; native processor is planned",advanced:"VST3/AU, bounded preset generation, role-specific routing",lesson:"Recording quality and vocal-chain decisions",prompt:"Help me build a vocal chain. Ask about my dry take, voice, DAW, and delivery first."},
  {id:"beat-compass",name:"Beat Compass",purpose:"Choose production that supports the voice.",audience:"Independent artists",problem:"Choosing a beat that fights the performance",features:["Candidate comparison","Vocal-space rubric","License notes"],workflow:"Compare three beats using one concept and vocal idea",ui:"Three cards, shared audition, decision notes",ai:"Explain density, energy, and delivery tradeoffs",presets:["Aggressive Rap","Melodic Lead","Club Crossover"],mvp:"Guided comparison brief",advanced:"Audio features and vocal overlays",lesson:"Beat selection",prompt:"Guide me through comparing three beats against my voice and song concept."},
  {id:"pocket",name:"Pocket Lab",purpose:"Make drums support the vocal pocket.",audience:"Beatmakers",problem:"Busy drums without performance space",features:["Rhythm templates","Swing","Density","MIDI export"],workflow:"Select intent → compare groove → simplify → export",ui:"Step grid and vocal guide lane",ai:"Suggest accents, rests, and section changes",presets:["Sparse Pressure","Southern Bounce","Rolling Trap"],mvp:"Rhythm planning brief; MIDI engine planned",advanced:"DAW MIDI plugin and vocal-informed variations",lesson:"Drum roles and groove",prompt:"Help me design a drum pocket that leaves room for fast rap delivery."},
  {id:"melody",name:"Melody Space",purpose:"Leave useful room around the lead.",audience:"Producers",problem:"Melody competing with the artist",features:["Register review","Density","Voicing alternatives"],workflow:"Review melody and vocal range → simplify → compare",ui:"Piano roll, range overlay, variation panel",ai:"Explain register and rhythm choices",presets:["Dark Minimal","Warm Motion","Open Hook"],mvp:"Melody decision brief",advanced:"MIDI transformations and audio-to-MIDI",lesson:"Harmony, emotion, and vocal space",prompt:"Help me simplify a melody so it supports rather than masks the vocal."},
  {id:"hook",name:"Hook Lab",purpose:"Strengthen the central refrain.",audience:"Songwriters and artists",problem:"Clear concept without memorable delivery",features:["Lyric rubric","Alternatives","Preserve-copy option","Version comparison"],workflow:"Share hook → assess contrast → test one change",ui:"Original and alternatives beside criteria",ai:"Review cadence and wording; request audio for delivery claims",presets:["Chant","Statement","Melodic Refrain"],mvp:"Text-based coaching in Studio Brain",advanced:"Audio contrast and listener comparisons",lesson:"Hooks and repetition",prompt:"Review my hook for clarity, cadence, contrast, and memorability. Preserve my original wording unless I authorize changes."},
  {id:"arrangement",name:"Arrangement Director",purpose:"Author the progression of the song.",audience:"Artists and producers",problem:"Repetition and weak section handoffs",features:["Section map","Energy plan","Transition notes"],workflow:"Map sections → identify weak handoff → audition revision",ui:"Timeline with section notes",ai:"Suggest entrances, cuts, and transitions with reasons",presets:["Rap Single","Narrative Song","Performance Edit"],mvp:"Annotated arrangement plan",advanced:"Section detection and marker export",lesson:"Escalation and transitions",prompt:"Help me map my song's sections and improve transitions without rewriting approved material."},
  {id:"readiness",name:"Mix Readiness",purpose:"Prepare files for an engineer.",audience:"Home-recording artists",problem:"Incomplete or unsuitable mix submissions",features:["Format review","Clipping checks","Alignment","Delivery checklist"],workflow:"Inspect files → fix blockers → prepare brief",ui:"Blockers, evidence, and next steps",ai:"Explain actual findings; never invent measurements",presets:["Vocal Mix Delivery","Multitrack Delivery","Mastering Submission"],mvp:"Submission checklist; existing project analysis stays in Music OS",advanced:"Validated multitrack checks and engineer review",lesson:"Recording and handoff standards",prompt:"Check my project's mix-readiness using available measurements and a delivery checklist. Identify missing evidence."},
  {id:"identity",name:"Artist Identity",purpose:"Connect music and visual positioning.",audience:"Independent artists",problem:"An inconsistent artist world",features:["Identity intake","Reference reasoning","Content pillars"],workflow:"Define audience → review references → approve brief",ui:"Identity canvas and reference board",ai:"Identify contradictions without inventing biography",presets:["Reintroduction","New Era","Album Campaign"],mvp:"Editable identity brief through chat",advanced:"Asset comparisons and human review",lesson:"Branding and audience",prompt:"Help me build an artist identity brief that connects sound, audience, visuals, and content."},
  {id:"release",name:"Release Director",purpose:"Turn a release into an executable schedule.",audience:"Independent artists and teams",problem:"Uploading before assets and rights are ready",features:["Reverse calendar","Metadata","Asset tracker","Extension plan"],workflow:"Choose date → identify blockers → assign work → review",ui:"Readiness board and calendar",ai:"Adjust plan to resources; do not publish automatically",presets:["Debut Single","EP","Album"],mvp:"Project-aware release guidance and existing Release Center",advanced:"Approved integrations and reporting",lesson:"Release strategy",prompt:"Help me build a release rollout from my project's current readiness, date, rights, and assets."},
  {id:"forge",name:"Preset Forge",purpose:"Make approved decisions reproducible.",audience:"Producers",problem:"Useful settings cannot be reliably recreated",features:["Schema bounds","Compatibility","Versions","Audition notes"],workflow:"Select supported processor → propose → audition → approve",ui:"Intent and parameter comparison",ai:"Generate only supported bounded parameter proposals",presets:["Founder Templates","Artist Variations"],mvp:"Preset specification drafts; processor adapter planned",advanced:"TM processor exports and curated catalog",lesson:"Repeatable decisions",prompt:"Draft a reproducible vocal preset specification from my DNA. Separate creative intent from untested parameter values."}
];
export function retrieveKnowledge(question:string): KnowledgeCard[] {
  const terms = question.toLowerCase().match(/[a-z0-9]+/g)?.filter(t => t.length > 2) ?? [];
  return knowledge.map(card => ({card, score:terms.reduce((sum,t)=>sum+(card.topic.toLowerCase().includes(t)?4:0)+(card.title.toLowerCase().includes(t)?3:0)+(card.guidance.toLowerCase().includes(t)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,4).map(x=>x.card);
}
