/**
 * Batch 003 — Atlanta Trap / Modern Rap Production Trees (PDNA-000081–105).
 */

import type { BatchSeedEntry } from "@/lib/producer-dna/seed/types";
import { capsuleDefaults } from "@/lib/producer-dna/seed/types";

const d = capsuleDefaults;

const entry = (
  id: string,
  name: string,
  regionScene: string,
  coreDnaAngle: string,
  region: string,
  sceneMovement: string,
  primaryGenres: string[],
  signatureSoundSummary: string,
  artisticDna: string,
  rhythmicDna: string,
  melodicHarmonicDna: string,
  arrangementDna: string,
  typeBeatInspiredDirection: string,
  originalityTwist: string
): BatchSeedEntry => ({
  id,
  name,
  regionScene,
  coreDnaAngle,
  country: "United States",
  region,
  primaryGenres,
  sceneMovement,
  signatureSoundSummary,
  artisticDna,
  technicalDna: d().technicalDna,
  rhythmicDna,
  melodicHarmonicDna,
  arrangementDna,
  typeBeatInspiredDirection,
  originalityTwist,
  researchConfidence: d().researchConfidence
});

export const BATCH_003_SEED: BatchSeedEntry[] = [
  entry(
    "PDNA-000081",
    "Shawty Redd",
    "Atlanta crunk/trap precursor",
    "Crunk-to-trap bridge, dark synths, early Atlanta street energy",
    "Atlanta, Georgia",
    "Crunk era, early trap precursor",
    ["crunk", "trap", "southern rap"],
    "Dark synth stabs, crunk energy, early trap menace, and trunk-rattling simplicity.",
    "Shawty Redd turns crunk into trap's ancestor — aggression through minimal synth and heavy kick.",
    "Crunk kick patterns, marching snare energy, pre-trap hat patterns.",
    "Minor synth stabs, simple hypnotic loops.",
    "Hook-first crunk intro, energy sustain.",
    "Dark crunk-trap hybrid with synth stab hooks. Avoid copying Shawty Redd's specific crunk patterns.",
    "Shawty Redd darkness on UK drill sliding bass."
  ),
  entry(
    "PDNA-000082",
    "Drumma Boy",
    "Memphis/Atlanta crossover",
    "Orchestral trap, brass aggression, cinematic Southern rap",
    "Atlanta, Georgia",
    "Drum Squad, orchestral trap",
    ["trap", "southern rap", "crunk"],
    "Orchestral brass, cinematic trap, hard 808, and Southern anthem scale.",
    "Drumma Boy scores the strip — brass is horn section for the club.",
    "Hard trap hats, 808 authority, orchestral percussion layers.",
    "Brass stabs, minor cinematic chords, anthemic hooks.",
    "Brass intro, drop to 808, chorus brass lift.",
    "Orchestral trap with brass stabs and hard 808. Avoid copying Drumma Boy anthem patterns.",
    "Drumma Boy brass on amapiano log-drum groove."
  ),
  entry(
    "PDNA-000083",
    "DJ Toomp",
    "Atlanta snap/trap foundation",
    "Snap music architecture, 808 clap science, pre-trap Atlanta",
    "Atlanta, Georgia",
    "Snap music, trap foundation",
    ["snap", "trap", "southern rap"],
    "Snap clap patterns, 808 foundation, Atlanta club science, and bounce minimalism.",
    "Toomp defines snap — the clap is the hook, the 808 is the law.",
    "Snap clap on beat 3, 808 kick patterns, sparse hats.",
    "Simple minor loops, club hook simplicity.",
    "Snap intro, clap hook, trunk sustain.",
    "Snap-trap beat with clap-forward hook. Avoid copying Dope Boyz snap patterns.",
    "DJ Toomp snap on dembow kick hybrid."
  ),
  entry(
    "PDNA-000084",
    "Jermaine Dupri",
    "So So Def Atlanta",
    "So So Def polish, early Atlanta pop-rap, bass-heavy club",
    "Atlanta, Georgia",
    "So So Def Records",
    ["hip-hop", "R&B", "southern rap"],
    "So So Def bass, polished Southern club, early Atlanta crossover.",
    "Dupri makes Atlanta sound national before trap took over — bass is brand.",
    "Club bounce, bass-heavy kick, R&B tempo flexibility.",
    "Major-key hooks, R&B chord movement.",
    "Bass intro, hook chorus, polished verse.",
    "So So Def bounce with bass-heavy club energy. Avoid copying So So Def signature bass lines.",
    "Dupri bounce on Afrobeats percussion."
  ),
  entry(
    "PDNA-000085",
    "Fatboi",
    "Atlanta trap pioneer",
    "Early trap 808 science, Peel Street era, foundational darkness",
    "Atlanta, Georgia",
    "Early Atlanta trap",
    ["trap", "southern rap"],
    "Early trap 808 patterns, dark loops, foundational Atlanta menace.",
    "Fatboi helps invent trap's physics — 808 as emotional weapon before the genre had a name.",
    "Early trap hat rolls, hard 808, sparse drums.",
    "Dark minor two-chord loops.",
    "Loop intro, 808 drop, minimal variation.",
    "Early trap darkness with hard 808 and sparse melody. Avoid copying foundational trap loops.",
    "Fatboi early trap on phonk cowbell layers."
  ),
  entry(
    "PDNA-000086",
    "Will-A-Fool",
    "Atlanta trap",
    "Hard trap drums, street energy, club-ready aggression",
    "Atlanta, Georgia",
    "Atlanta trap scene",
    ["trap", "southern rap"],
    "Hard trap drums, street aggression, club-ready 808 pressure.",
    "Will-A-Fool keeps trap physical — drums hit like confrontation.",
    "Hard snare, rapid hats, 808 distortion.",
    "Dark simple loops, street narrative minor keys.",
    "Drum intro, hook loop, energy sustain.",
    "Hard street trap with aggressive 808. Avoid copying Will-A-Fool drum signatures.",
    "Will-A-Fool aggression on Brazilian funk tamborzão."
  ),
  entry(
    "PDNA-000087",
    "London on da Track",
    "Atlanta melodic trap",
    "Melodic trap architecture, guitar/synth hybrid hooks, modern ATL pop-rap",
    "Atlanta, Georgia",
    "Modern melodic trap",
    ["trap", "melodic rap", "pop rap"],
    "Melodic trap guitars, airy synths, hook-first architecture, and modern ATL gloss.",
    "London makes trap sing — melody is not weakness, it is the new menace.",
    "Trap hat rolls, melodic bounce, 808 slides.",
    "Guitar loops, major/minor hook melodies.",
    "Guitar hook intro, verse space, chorus lift.",
    "Melodic trap with guitar/synth hook and 808 slides. Avoid copying London's specific guitar loops.",
    "London melodic trap on UK garage shuffle."
  ),
  entry(
    "PDNA-000088",
    "TM88",
    "808 Mafia / Atlanta",
    "Dark atmospheric trap, Night Lovell aesthetic, 808 Mafia lineage",
    "Atlanta, Georgia",
    "808 Mafia, atmospheric trap",
    ["trap", "cloud rap"],
    "Dark atmospheric pads, 808 Mafia darkness, cinematic trap space.",
    "TM88 paints trap in shadows — atmosphere is half the intimidation.",
    "Rolling hats, slow trap urgency, 808 sub weight.",
    "Dark pad loops, minor atmospheric synths.",
    "Atmospheric intro, 808 entrance, space sustain.",
    "Dark atmospheric trap with pad space and 808 weight. Avoid copying 808 Mafia dark templates.",
    "TM88 atmosphere on ambient drone layers."
  ),
  entry(
    "PDNA-000089",
    "Sonny Digital",
    "Atlanta trap",
    "Bouncy dark trap, Metro-adjacent, hook-centric darkness",
    "Atlanta, Georgia",
    "Modern Atlanta trap",
    ["trap", "hip-hop"],
    "Bouncy dark trap, catchy minor loops, Metro-adjacent energy.",
    "Sonny Digital makes darkness danceable — trap bounce without losing menace.",
    "Bouncy trap hats, 808 knock, mid-tempo urgency.",
    "Minor catchy loops, simple hook intervals.",
    "Hook-first drop, verse pocket, repeat.",
    "Bouncy dark trap with catchy minor loop. Avoid copying Sonny Digital hook patterns.",
    "Sonny bounce on reggaeton dembow."
  ),
  entry(
    "PDNA-000090",
    "Wheezy",
    "Atlanta melodic trap",
    "Flute/synth melody traps, Young Thug era, weird hook science",
    "Atlanta, Georgia",
    "Young Thug production era",
    ["trap", "melodic rap", "experimental rap"],
    "Flute melodies, weird synth hooks, melodic trap experimentation.",
    "Wheezy makes trap whimsical and dangerous — odd melodies become earworms.",
    "Trap bounce, playful hat patterns, 808 underpinning.",
    "Flute/synth lead hooks, unconventional scales.",
    "Melodic hook intro, beat switch potential, playful drops.",
    "Melodic trap with unusual flute/synth hook. Avoid copying Wheezy's specific melodies.",
    "Wheezy weird melody on Japanese city pop chords."
  ),
  entry(
    "PDNA-000091",
    "Turbo",
    "Atlanta trap",
    "Gunna melodic trap, smooth 808 glide, luxury trap aesthetic",
    "Atlanta, Georgia",
    "Melodic trap, Gunna era",
    ["trap", "melodic rap"],
    "Smooth 808 glide, luxury trap aesthetic, melodic simplicity.",
    "Turbo makes trap sound expensive — glide and space imply wealth.",
    "Smooth hats, gliding 808, relaxed trap tempo.",
    "Simple luxury minor loops, clean synth pads.",
    "Smooth intro, groove sustain, hook via melody.",
    "Luxury melodic trap with gliding 808. Avoid copying Turbo/Gunna loop fingerprints.",
    "Turbo luxury glide on amapiano piano."
  ),
  entry(
    "PDNA-000092",
    "Pierre Bourne",
    "Atlanta/Internet trap",
    "Psychedelic trap, Pi'erre Bourne tag, spacey melodic loops",
    "Atlanta, Georgia",
    "Playboi Carti era, internet trap",
    ["trap", "cloud rap", "experimental"],
    "Spacey melodic loops, psychedelic trap, Pi'erre tag culture.",
    "Pierre makes trap feel weightless — space and repetition become hypnosis.",
    "Sparse hats, bouncy 808, psychedelic tempo feel.",
    "Spacey synth loops, simple trippy melodies.",
    "Loop mantra, tag culture, minimal arrangement.",
    "Spacey psychedelic trap loop with bounce. Avoid copying Pierre's tag and loop patterns.",
    "Pierre space on hyperpop distortion."
  ),
  entry(
    "PDNA-000093",
    "Nick Mira",
    "Internet trap / Juice WRLD",
    "Emo-trap guitar loops, Internet Money, melodic sadness",
    "Virginia / Atlanta-adjacent",
    "Internet Money, emo-trap",
    ["trap", "emo rap", "melodic rap"],
    "Guitar-led emo-trap, melodic sadness, Internet Money bounce.",
    "Nick Mira scores heartbreak over trap — guitar loop is diary entry.",
    "Trap hats, emotional mid-tempo, 808 under guitar.",
    "Guitar loops, minor emo chord progressions.",
    "Guitar intro hook, verse sustain, chorus lift.",
    "Emo-trap with guitar loop hook and trap drums. Avoid copying Nick Mira/Juice WRLD loops.",
    "Nick Mira emo guitar on drill tempo."
  ),
  entry(
    "PDNA-000094",
    "Cubeatz",
    "Melodic trap duo",
    "Cinematic melodic trap, Travis Scott adjacency, widescreen hooks",
    "Toronto/Atlanta crossover",
    "Modern cinematic trap",
    ["trap", "melodic rap"],
    "Cinematic melodic trap, widescreen synths, Travis-era scale.",
    "Cubeatz produce IMAX trap — hooks feel panoramic.",
    "Trap rolls, stadium energy, 808 foundation.",
    "Cinematic synth leads, anthemic minor hooks.",
    "Build intro, drop, chorus scale lift.",
    "Cinematic trap with widescreen synth hook. Avoid copying Cubeatz/Travis patterns.",
    "Cubeatz cinema on orchestral Afrobeat brass."
  ),
  entry(
    "PDNA-000095",
    "ATL Jacob",
    "Atlanta trap",
    "Future metro melodic trap, sleek darkness, modern hook science",
    "Atlanta, Georgia",
    "Future, modern ATL trap",
    ["trap", "melodic rap"],
    "Sleek modern trap, Future-adjacent darkness, hook science.",
    "ATL Jacob polishes trap for radio without sanding off menace.",
    "Clean hat rolls, tight 808, modern trap grid.",
    "Dark melodic hooks, sleek synth design.",
    "Hook-first, verse pocket, polished outro.",
    "Sleek modern trap with dark melodic hook. Avoid copying ATL Jacob/Future templates.",
    "ATL Jacob sleekness on Latin trap guitar."
  ),
  entry(
    "PDNA-000096",
    "Honorable C.N.O.T.E.",
    "Atlanta trap",
    "Darker trap loops, street narrative, raw ATL energy",
    "Atlanta, Georgia",
    "Atlanta underground trap",
    ["trap", "southern rap"],
    "Raw trap loops, street darkness, unpolished menace.",
    "C.N.O.T.E. keeps trap close to the street — rough edges are honesty.",
    "Hard drums, dark hat patterns, 808 pressure.",
    "Minimal dark loops, no gloss.",
    "Loop sustain, raw energy, minimal bridge.",
    "Raw dark trap loop with street energy. Avoid copying specific C.N.O.T.E. loops.",
    "C.N.O.T.E. rawness on lo-fi house."
  ),
  entry(
    "PDNA-000097",
    "Dun Deal",
    "Atlanta trap",
    "Gucci Mane era trap, street hook loops, foundational ATL",
    "Atlanta, Georgia",
    "Gucci Mane trap era",
    ["trap", "southern rap"],
    "Gucci-era trap loops, street hooks, foundational Atlanta sound.",
    "Dun Deal helps define trap's first golden era — loops are street anthems.",
    "Classic trap hats, 808 knock, mid-tempo bounce.",
    "Simple minor hook loops.",
    "Hook loop intro, verse repeat.",
    "Classic Gucci-era trap loop with 808 bounce. Avoid copying Dun Deal specific loops.",
    "Dun Deal classic trap on dembow."
  ),
  entry(
    "PDNA-000098",
    "Go Grizzly",
    "Atlanta trap",
    "Hard trap bounce, street energy, club pressure",
    "Atlanta, Georgia",
    "Modern Atlanta trap",
    ["trap", "southern rap"],
    "Hard trap bounce, club pressure, aggressive 808.",
    "Go Grizzly pushes trap into redline — energy is the composition.",
    "Fast hats, hard kick, distorted 808.",
    "Dark aggressive loops.",
    "Energy intro, sustain, dropouts for DJ.",
    "High-energy trap with hard 808 pressure. Avoid copying Go Grizzly drum aggression.",
    "Go Grizzly energy on footwork tempo."
  ),
  entry(
    "PDNA-000099",
    "Pooh Beatz",
    "Atlanta trap",
    "Migos offset flow trap, bouncy dark loops",
    "Atlanta, Georgia",
    "Migos era trap",
    ["trap", "southern rap"],
    "Migos-adjacent bounce, triplet-ready trap, dark catchy loops.",
    "Pooh Beatz builds beats for triplet flow — bounce anticipates cadence.",
    "Bouncy trap, triplet hat friendly, 808 glide.",
    "Dark catchy two-chord loops.",
    "Loop hook, verse triplet space, repeat.",
    "Bouncy trap for triplet flow with dark loop. Avoid copying Migos-era Pooh Beatz patterns.",
    "Pooh Beatz bounce on UK grime."
  ),
  entry(
    "PDNA-000100",
    "Taurus",
    "808 Mafia",
    "808 Mafia darkness, heavy 808 distortion, trap minimalism",
    "Atlanta, Georgia",
    "808 Mafia",
    ["trap", "southern rap"],
    "808 Mafia heavy distortion, dark minimalism, trap pressure.",
    "Taurus distorts the 808 until it becomes texture — minimal elements, maximum weight.",
    "Distorted 808, machine-gun hats, sparse melody.",
    "Dark pad or single-note loop.",
    "808 intro, darkness sustain.",
    "808 Mafia style distorted trap with minimal melody. Avoid copying 808 Mafia templates.",
    "Taurus 808 distortion on industrial noise layers."
  ),
  entry(
    "PDNA-000101",
    "K.E. on the Track",
    "Atlanta trap",
    "Bouncy trap hooks, radio-ready street loops",
    "Atlanta, Georgia",
    "Atlanta trap/pop crossover",
    ["trap", "pop rap"],
    "Radio-ready trap hooks, bouncy loops, street-pop crossover.",
    "K.E. bridges trap and radio — hooks are product, drums are credibility.",
    "Bouncy trap grid, clean 808, pop-ready tempo.",
    "Catchy minor/major hook loops.",
    "Hook intro, chorus lift, polished verse.",
    "Radio-ready bouncy trap with catchy hook. Avoid copying K.E. hook patterns.",
    "K.E. pop-trap on K-pop synth gloss."
  ),
  entry(
    "PDNA-000102",
    "CPA Live",
    "Atlanta trap",
    "Live instrument trap hybrid, organic trap bounce",
    "Atlanta, Georgia",
    "Live-trap hybrid ATL",
    ["trap", "southern rap"],
    "Live keys/guitar over trap drums, organic bounce hybrid.",
    "CPA Live humanizes trap — live fingers on trap grid.",
    "Trap drums under live instrument pocket.",
    "Live chord loops, organic melodic hooks.",
    "Live intro, trap drop, hybrid sustain.",
    "Live instrument trap hybrid with organic bounce. Avoid copying specific CPA Live arrangements.",
    "CPA Live hybrid on jazz fusion chords."
  ),
  entry(
    "PDNA-000103",
    "Buddah Bless",
    "Atlanta trap",
    "Hard trap knock, street anthem loops, DJ Esco era energy",
    "Atlanta, Georgia",
    "Atlanta trap anthems",
    ["trap", "southern rap"],
    "Hard trap knock, anthemic street loops, trunk-ready energy.",
    "Buddah Bless makes trap feel like a rally — every beat is a call to move.",
    "Hard 808 knock, aggressive hats, anthem tempo.",
    "Dark catchy hook loops.",
    "Knock intro, hook repeat, energy sustain.",
    "Anthemic hard trap with knock-heavy 808. Avoid copying Buddah Bless knock patterns.",
    "Buddah Bless knock on dembow kick."
  ),
  entry(
    "PDNA-000104",
    "OG Parker",
    "Atlanta trap",
    "Migos flow trap, bouncy hook science, Quality Control era",
    "Atlanta, Georgia",
    "Quality Control, Migos era",
    ["trap", "southern rap"],
    "QC bounce, Migos-flow trap, hook-first club science.",
    "OG Parker builds beats for three voices — bounce is conversational.",
    "Bouncy trap, triplet-ready hats, 808 glide.",
    "Simple dark catchy loops.",
    "Hook loop, verse triplet space.",
    "QC-style bouncy trap for group flow. Avoid copying OG Parker/QC loop patterns.",
    "OG Parker bounce on Afrobeats guitar."
  ),
  entry(
    "PDNA-000105",
    "Purps",
    "808 Mafia",
    "808 Mafia minimal darkness, sparse trap menace",
    "Atlanta, Georgia",
    "808 Mafia",
    ["trap", "southern rap"],
    "808 Mafia sparse darkness, minimal elements, heavy sub pressure.",
    "Purps strips trap to bone — what remains is pure menace.",
    "Sparse hats, distorted 808, minimal percussion.",
    "Single dark loop or pad.",
    "808 intro, minimal sustain.",
    "Minimal 808 Mafia darkness with sparse melody. Avoid copying 808 Mafia templates.",
    "Purps minimal trap on ambient drone."
  )
];
