/**
 * Batch 002 — Hip-Hop Foundations (PDNA-000051–080).
 * Regional scene founders, sampling pioneers, drum architecture innovators.
 */

import type { BatchSeedEntry } from "@/lib/producer-dna/seed/types";
import { capsuleDefaults } from "@/lib/producer-dna/seed/types";

const d = capsuleDefaults;

const entry = (
  id: string,
  name: string,
  regionScene: string,
  coreDnaAngle: string,
  region: string,
  sceneMovement: string,
  primaryGenres: string[],
  signatureSoundSummary: string,
  artisticDna: string,
  rhythmicDna: string,
  melodicHarmonicDna: string,
  arrangementDna: string,
  typeBeatInspiredDirection: string,
  originalityTwist: string
): BatchSeedEntry => ({
  id,
  name,
  regionScene,
  coreDnaAngle,
  country: "United States",
  region,
  primaryGenres,
  sceneMovement,
  signatureSoundSummary,
  artisticDna,
  technicalDna: d().technicalDna,
  rhythmicDna,
  melodicHarmonicDna,
  arrangementDna,
  typeBeatInspiredDirection,
  originalityTwist,
  researchConfidence: d().researchConfidence
});

export const BATCH_002_SEED: BatchSeedEntry[] = [
  entry(
    "PDNA-000051",
    "Afrika Bambaataa",
    "Bronx electro hip-hop",
    "Electro-funk bridge, breakbeat architecture, Zulu Nation sound",
    "Bronx, New York",
    "Universal Zulu Nation, electro hip-hop",
    ["hip-hop", "electro", "funk"],
    "Electro-funk fusion, breakbeat collage, robotic vocoder hooks, and party-break architecture.",
    "Bambaataa maps breakdance culture to electronic funk — the beat is geography, the synth is future.",
    "Breakbeat-driven 808/electro pulse, syncopated kick, robotic grid with funk swing.",
    "Minor electro hooks, Kraftwerk-influenced synth lines, funk chord stabs.",
    "DJ-friendly intro, break section, vocoder hook statement.",
    "Electro-hip-hop with breakbeat foundation and robotic synth hooks. Avoid copying Planet Rock.",
    "Bambaataa electro logic with amapiano log-drum or UK garage shuffle."
  ),
  entry(
    "PDNA-000052",
    "Larry Smith",
    "Queens/Run-DMC era",
    "Drum machine minimalism, rap-rock bridge, hard drum authority",
    "Queens, New York",
    "Def Jam early era, Run-DMC",
    ["hip-hop", "rap-rock"],
    "Hard drum machine beats, minimal samples, rap-rock punch, and street-level simplicity.",
    "Smith proves less is more — drum machine and vocal are the entire architecture.",
    "TR-808 kick/snare authority, no swing apology, straight hard grid.",
    "Sparse melodic content; guitar or sample stab as hook.",
    "Intro drum statement, verse sustain, hook via vocal or guitar stab.",
    "Hard minimal drum machine beat with sparse melodic accent. Avoid copying Run-DMC drum patterns.",
    "Larry Smith hardness on Brazilian tamborzão syncopation."
  ),
  entry(
    "PDNA-000053",
    "Arthur Baker",
    "Bronx/electro production",
    "Planet Rock electro architecture, 808 + Roland fusion",
    "Bronx, New York",
    "Electro hip-hop foundation",
    ["electro", "hip-hop", "funk"],
    "808-meets-electro sequencing, Planet Rock architecture, and club-electro propulsion.",
    "Baker wires machines into hip-hop before hip-hop knew it needed machines.",
    "Four-on-the-floor electro pulse, 808 tom fills, sequencer precision.",
    "Synth lead hooks, minor electro melody, vocoder color.",
    "Machine build, drop to full electro groove.",
    "Electro-808 hybrid with sequencer propulsion. Avoid copying Planet Rock synth lines.",
    "Baker electro-808 on dembow kick pattern."
  ),
  entry(
    "PDNA-000054",
    "Hank Shocklee",
    "Long Island/Public Enemy",
    "Bomb Squad collage, noise-as-structure, maximal sample density",
    "Long Island, New York",
    "The Bomb Squad, Public Enemy",
    ["hip-hop", "political rap", "experimental"],
    "Maximal sample collage, noise layers, sirens, and revolutionary sonic density.",
    "Shocklee treats samples as orchestra — chaos is composed, noise is narrative.",
    "Layered breakbeats, stacked drum composites, irregular accents.",
    "Dissonant horn stabs, funk chaos, atonal sample clashes.",
    "Sudden dropouts, siren entrances, verse as collage not loop.",
    "Dense sample-collage beat with noise and siren accents. Avoid copying Public Enemy arrangements.",
    "Bomb Squad density with single-instrument constraint — one synth, maximum layers."
  ),
  entry(
    "PDNA-000055",
    "Easy Mo Bee",
    "Brooklyn golden era",
    "Smooth soul samples, laid-back Brooklyn elegance",
    "Brooklyn, New York",
    "Bad Boy early era, golden age Brooklyn",
    ["hip-hop", "boom bap", "soul"],
    "Smooth soul loops, laid-back drums, Brooklyn elegance, and sample warmth.",
    "Easy Mo Bee makes toughness gentle — soul samples carry street narrative without aggression.",
    "Laid-back boom-bap, soft kick, crisp snare, head-nod not battle.",
    "Soul chord loops, jazz-inflected samples, major/minor warmth.",
    "Loop sustain with filter evolution, vocal-forward mix space.",
    "Smooth soul-sample boom bap with laid-back drums. Avoid copying Notorious B.I.G. early loops.",
    "Easy Mo Bee soul warmth on drill tempo with melodic rap space."
  ),
  entry(
    "PDNA-000056",
    "Clark Kent",
    "Brooklyn production",
    "Hard kicks, soul chops, Brooklyn club authority",
    "Brooklyn, New York",
    "Brooklyn golden era, Def Jam",
    ["hip-hop", "boom bap"],
    "Hard kick drums, soul sample chops, Brooklyn authority, and club-ready punch.",
    "Clark Kent's drums hit first — samples serve the knock, not the other way around.",
    "Hard kick prominence, snare crack, boom-bap with club weight.",
    "Soul loops, horn stabs, catchy sample hooks.",
    "Knock-first intro, hook via sample or vocal, DJ outro.",
    "Hard-knock boom bap with soul chop hooks. Avoid copying Clark Kent's Jay-Z era drum sounds.",
    "Clark Kent knock on Afrobeats percussion bed."
  ),
  entry(
    "PDNA-000057",
    "DJ Quik",
    "Compton/West Coast",
    "G-funk live-musician feel, talk box, West Coast pocket",
    "Compton, California",
    "West Coast G-funk, Quik's Playhouse",
    ["hip-hop", "G-funk", "west coast"],
    "Live-musician G-funk, talk box, slick synth leads, and West Coast pocket glide.",
    "Quik plays every part — the beat breathes because human fingers not grids made it.",
    "Laid-back West Coast swing, funk drummer pocket, glide not bounce.",
    "Synth leads, funk chords, talk box as melodic instrument.",
    "Funk intro, groove sustain, talk box hook.",
    "Live-feel G-funk with synth lead and talk box space. Avoid copying Quik's exact synth melodies.",
    "Quik pocket on UK funky shuffle with talk box on amapiano."
  ),
  entry(
    "PDNA-000058",
    "Battlecat",
    "Los Angeles West Coast",
    "G-funk synthesis, Moog bass, cinematic West Coast warmth",
    "Los Angeles, California",
    "West Coast G-funk, Death Row era",
    ["hip-hop", "G-funk", "west coast"],
    "Moog bass warmth, G-funk synth pads, cinematic West Coast atmosphere.",
    "Battlecat's Moog is the emotional anchor — synths carry California sunset menace.",
    "Laid-back G-funk grid, lazy hi-hats, deep kick.",
    "Moog bass lines, minor key synth pads, funk guitar.",
    "Synth intro, groove drop, cinematic bridge.",
    "G-funk with Moog bass warmth and cinematic pads. Avoid copying Battlecat's Snoop-era motifs.",
    "Battlecat Moog warmth on Latin trap dembow."
  ),
  entry(
    "PDNA-000059",
    "Mannie Fresh",
    "New Orleans bounce",
    "Bounce architecture, call-and-response, party groove science",
    "New Orleans, Louisiana",
    "Cash Money, New Orleans bounce",
    ["hip-hop", "bounce", "southern rap"],
    "Bounce kick patterns, call-and-response hooks, party groove, and New Orleans swing.",
    "Mannie makes every track a block party — bounce is community rhythm science.",
    "Bounce kick (tresillo-influenced), handclap accents, high energy pocket.",
    "Simple earworm hooks, call-and-response chants, major key party.",
    "Hook-first, bounce sustain, breakdown to drums and chants.",
    "New Orleans bounce with call-and-response hook space. Avoid copying Mannie Fresh bounce patterns.",
    "Mannie bounce on UK drill hats with melodic rap verses."
  ),
  entry(
    "PDNA-000060",
    "DJ Paul",
    "Memphis horrorcore",
    "Dark Memphis loops, lo-fi menace, early trap DNA",
    "Memphis, Tennessee",
    "Three 6 Mafia, Memphis underground",
    ["hip-hop", "horrorcore", "trap"],
    "Dark lo-fi loops, Memphis menace, early 808/trap DNA, and horror atmosphere.",
    "DJ Paul builds dread from cheap equipment — lo-fi is feature, darkness is brand.",
    "Slow-to-mid tempo trap precursors, rolling hi-hats, hard 808.",
    "Minor key loops, horror movie samples, eerie synths.",
    "Atmospheric intro, dark loop sustain, ad-lib layers.",
    "Dark lo-fi Memphis beat with horror atmosphere. Avoid copying Three 6 Mafia loops.",
    "Memphis darkness on Brazilian phonk cowbell patterns."
  ),
  entry(
    "PDNA-000061",
    "Juicy J",
    "Memphis trap evolution",
    "Lex Luger bridge, triplet hats, Memphis-to-trap pipeline",
    "Memphis, Tennessee",
    "Three 6 Mafia, Memphis trap",
    ["hip-hop", "trap", "southern rap"],
    "Memphis darkness evolving into triplet hats, 808 evolution, and club trap energy.",
    "Juicy J carries Memphis into modern trap — darkness learns to party harder.",
    "Triplet hi-hats, 808 slides, Memphis slow-rolling to trap urgency.",
    "Dark minor loops, simple hypnotic hooks.",
    "Beat drop architecture, hook repeat, energy sustain.",
    "Memphis-dark trap with triplet hats and 808 slides. Avoid copying Juicy J tag patterns.",
    "Juicy J darkness with dembow kick hybrid."
  ),
  entry(
    "PDNA-000062",
    "No I.D.",
    "Chicago conscious rap",
    "Soulful sample sophistication, Chicago introspection",
    "Chicago, Illinois",
    "Chicago hip-hop, Roc-A-Fella era",
    ["hip-hop", "conscious rap", "soul"],
    "Soulful sample sophistication, Chicago introspection, and polished boom-bap.",
    "No I.D. bridges Chicago soul conscience and mainstream polish — samples think before they knock.",
    "Clean boom-bap, measured swing, kick/snare clarity.",
    "Soul samples, gospel chord color, introspective harmony.",
    "Sample intro, verse loop, chorus lift via vocal or strings.",
    "Soulful Chicago boom bap with introspective sample loops. Avoid copying Common/ Kanye early chops.",
    "No I.D. soul on electronic ambient pads."
  ),
  entry(
    "PDNA-000063",
    "Kanye West",
    "Chicago chipmunk soul",
    "Pitch-shifted soul, gospel scale, maximalist minimalism",
    "Chicago, Illinois",
    "Chipmunk soul era, Roc-A-Fella",
    ["hip-hop", "soul", "pop rap"],
    "Pitch-shifted soul samples, gospel scale, orchestral ambition, and emotional maximalism.",
    "Early Kanye makes soul sound childlike and sacred simultaneously — pitch-shift is emotion.",
    "Soul drum loops, sometimes sped, swung or straight depending on era.",
    "Gospel chords, pitched vocal samples, orchestral stabs in later work.",
    "Sample hook intro, beat drop, choir or string bridge.",
    "Chipmunk-soul beat with pitched vocal sample hooks. Avoid copying Kanye's exact soul flips.",
    "Chipmunk soul logic on Afrobeats guitar loops."
  ),
  entry(
    "PDNA-000064",
    "Large Professor",
    "Queens/Extra P",
    "Main Source grit, Queensbridge authority, raw sample elegance",
    "Queens, New York",
    "Main Source, Queensbridge",
    ["hip-hop", "boom bap"],
    "Raw sample elegance, Queensbridge authority, and Main Source grit.",
    "Extra P makes rough sound refined — the sample is dusty but the drum placement is professor-level.",
    "Hard snare, dusty kick, boom-bap with sample chop punctuation.",
    "Jazz/soul loops, horn samples, minor key grit.",
    "Scratch intro, loop verse, outro fade.",
    "Dusty boom bap with jazz sample elegance. Avoid copying Main Source breaks.",
    "Large Professor grit on lo-fi house chords."
  ),
  entry(
    "PDNA-000065",
    "Q-Tip",
    "Native Tongues jazz rap",
    "Jazz-quantized swing, Native Tongues warmth, abstract groove",
    "Queens, New York",
    "A Tribe Called Quest, Native Tongues",
    ["hip-hop", "jazz rap", "alternative hip-hop"],
    "Jazz-quantized swing, warm bass, abstract groove, and Native Tongues positivity.",
    "Tip's drums feel like they learned jazz before hip-hop — swing is philosophy not accident.",
    "Jazz swing on drums, loose hats, warm kick, conversational pocket.",
    "Jazz chord samples, upright bass feel, major/minor warmth.",
    "Loop evolution via bass line changes, subtle filter movement.",
    "Jazz-swing hip-hop with warm bass and abstract samples. Avoid copying Tribe drum feels.",
    "Q-Tip jazz swing on Brazilian bossa percussion."
  ),
  entry(
    "PDNA-000066",
    "Erick Sermon",
    "Def Squad funk",
    "Funk sample maximalism, EPMD loop science, Zapp influence",
    "Brentwood, New York",
    "EPMD, Def Squad",
    ["hip-hop", "funk", "boom bap"],
    "Funk sample loops, Zapp talkbox influence, EPMD loop science, and punchy drums.",
    "Sermon loops funk until it raps — the sample is the personality.",
    "Funk break science, hard snare, loop repetition.",
    "Zapp/Funkadelic samples, talkbox hooks, major funk chords.",
    "Loop intro, tag team verse structure, funk breakdown.",
    "Funk-loop boom bap with talkbox hook space. Avoid copying EPMD/Zapp flips.",
    "Def Squad funk on hyperpop synth distortion."
  ),
  entry(
    "PDNA-000067",
    "Pimp C",
    "UGK Houston",
    "Country rap, live instrumentation, Southern soul trunk music",
    "Port Arthur, Texas",
    "UGK, Southern hip-hop",
    ["hip-hop", "southern rap", "soul"],
    "Live instrumentation, country rap tone, Southern soul, and trunk-rattling warmth.",
    "Pimp C makes the South sound orchestral — live keys and soul samples in slow motion.",
    "Slow Southern bounce, live drum feel, trunk-rattling kick.",
    "Soul samples, live keys, gospel-influenced chords.",
    "Intro keys, verse groove, soulful hook.",
    "Slow Southern soul beat with live key loops. Avoid copying UGK's specific soul samples.",
    "Pimp C Southern soul on amapiano piano hypnosis."
  ),
  entry(
    "PDNA-000068",
    "Organized Noize",
    "Atlanta OutKast",
    "Live band funk, Dungeon Family architecture, Southern weirdness",
    "Atlanta, Georgia",
    "Dungeon Family, OutKast, Goodie Mob",
    ["hip-hop", "funk", "southern rap"],
    "Live band funk, Dungeon Family weirdness, and Southern rap architecture.",
    "Organized Noize treats rap like funk band music — live is the flex, weird is the brand.",
    "Live drummer funk pocket, clavinet, unconventional percussion.",
    "Funk chords, clavinet hooks, soul horn arrangements.",
    "Live intro, funk verse, horn hook chorus.",
    "Live-funk hip-hop with clavinet and horn hooks. Avoid copying OutKast's specific arrangements.",
    "Organized Noize live funk on electronic trap 808 sub."
  ),
  entry(
    "PDNA-000069",
    "Havoc",
    "Mobb Deep Queensbridge",
    "Dark piano loops, Queensbridge menace, minimal dread",
    "Queensbridge, New York",
    "Mobb Deep, Queensbridge hip-hop",
    ["hip-hop", "boom bap", "east coast"],
    "Dark piano loops, minimal dread, hard drums, and Queensbridge menace.",
    "Havoc paints noir with two sounds — dark piano and hard snare.",
    "Hard snare crack, simple kick pattern, no frills grid.",
    "Minor piano loops, eerie melodies, dark chord stasis.",
    "Piano intro, loop sustain, minimal variation.",
    "Dark piano boom bap with hard snare. Avoid copying Shook Ones piano loop.",
    "Havoc darkness on drill sliding 808s."
  ),
  entry(
    "PDNA-000070",
    "The Alchemist",
    "Culver City sample architect",
    "Psychedelic soul loops, grimy elegance, producer's producer craft",
    "Culver City, California",
    "Alc, Griselda, underground hip-hop",
    ["hip-hop", "underground", "boom bap"],
    "Psychedelic soul loops, grimy elegance, and producer's-producer sample craft.",
    "Alchemist makes dirt sound expensive — obscure samples become luxury through drum placement.",
    "Dusty drums, off-kilter swing, minimal variation.",
    "Obscure soul/psych loops, minor key, hypnotic repetition.",
    "Loop mantra, brief breakdown, return to loop.",
    "Grimy soul-loop beat with psychedelic texture. Avoid copying Alchemist's specific sample flips.",
    "Alchemist grime on Middle Eastern oud samples."
  ),
  entry(
    "PDNA-000071",
    "Just Blaze",
    "New York anthemic",
    "Soul anthem builds, horn stabs, Roc-A-Fella cinematic scale",
    "New York",
    "Roc-A-Fella, Jay-Z era",
    ["hip-hop", "boom bap", "anthemic"],
    "Anthemic soul builds, horn stabs, cinematic scale, and Roc-A-Fella grandeur.",
    "Just Blaze makes beats feel like stadiums — horns are architecture, builds are emotional events.",
    "Hard drums, snare rolls into chorus, boom-bap power.",
    "Soul samples, horn stabs, gospel scale builds.",
    "Slow build intro, horn drop, anthem chorus.",
    "Anthemic soul beat with horn stabs and build energy. Avoid copying Just Blaze's U Don't Know patterns.",
    "Just Blaze anthem scale on Afrobeats percussion."
  ),
  entry(
    "PDNA-000072",
    "9th Wonder",
    "North Carolina soul",
    "SP-1200 warmth, soul loop purity, Little Brother elegance",
    "Winston-Salem, North Carolina",
    "Little Brother, Soul Council",
    ["hip-hop", "soul", "boom bap"],
    "SP-1200 warmth, soul loop purity, and Little Brother elegance.",
    "9th Wonder proves one soul loop and perfect drums is enough — purity is the flex.",
    "SP-1200 crunch, head-nod swing, simple kick/snare.",
    "Soul vocal chops, warm chords, nostalgic major keys.",
    "Loop intro, sustain, minimal bridge.",
    "Warm soul-loop boom bap with SP texture. Avoid copying 9th Wonder's specific flips.",
    "9th Wonder warmth on Brazilian samba rhythm."
  ),
  entry(
    "PDNA-000073",
    "Hi-Tek",
    "Cincinnati soul",
    "Reflection Eternal warmth, soul jazz loops, Midwest conscience",
    "Cincinnati, Ohio",
    "Reflection Eternal, Midwest hip-hop",
    ["hip-hop", "soul", "conscious rap"],
    "Soul jazz loops, Midwest warmth, Reflection Eternal conscience, and clean drums.",
    "Hi-Tek makes conscience sound beautiful — soul jazz is the vehicle for truth.",
    "Clean boom-bap, moderate swing, kick clarity.",
    "Soul jazz samples, Rhodes chords, warm bass.",
    "Sample intro, verse loop, vocal hook focus.",
    "Soul-jazz boom bap with Rhodes warmth. Avoid copying Reflection Eternal loops.",
    "Hi-Tek soul jazz on UK garage shuffled hats."
  ),
  entry(
    "PDNA-000074",
    "Swizz Beatz",
    "Harlem bounce",
    "Ruff Ryders aggression, synth stabs, high-energy minimalism",
    "Harlem, New York",
    "Ruff Ryders, Harlem production",
    ["hip-hop", "east coast", "anthemic"],
    "Synth stab hooks, Ruff Ryders aggression, high-energy minimalism, and party anthems.",
    "Swizz makes one synth stab carry the whole song — aggression through simplicity.",
    "Hard kick, snare authority, high energy straight grid.",
    "Synth stab hooks, minimal melody, anthemic intervals.",
    "Stab intro, verse energy, hook via synth stab.",
    "High-energy beat with synth stab hook. Avoid copying Swizz's Ruff Ryders stabs.",
    "Swizz stab energy on reggaeton dembow."
  ),
  entry(
    "PDNA-000075",
    "Scott Storch",
    "Miami keys",
    "Keyboard melody hooks, Miami shine, pop-rap crossover",
    "Miami, Florida",
    "Miami production, pop-rap crossover",
    ["hip-hop", "pop rap", "southern rap"],
    "Keyboard melody hooks, Miami shine, and pop-rap crossover gloss.",
    "Storch puts keyboard melody first — the beat is a song before the rapper arrives.",
    "Mid-tempo bounce, crisp drums, keyboard-led rhythm.",
    "Keyboard hooks, Eastern scale color, major key shine.",
    "Keyboard intro hook, verse, chorus keyboard lift.",
    "Keyboard-hook beat with Miami gloss. Avoid copying Scott Storch's specific melodies.",
    "Storch keyboard hooks on amapiano log-drum counter-rhythm."
  ),
  entry(
    "PDNA-000076",
    "Daz Dillinger",
    "Long Beach G-funk",
    "Death Row lineage, funk guitar, West Coast party",
    "Long Beach, California",
    "Death Row, Dogg Pound",
    ["hip-hop", "G-funk", "west coast"],
    "Funk guitar loops, Death Row lineage, and West Coast party groove.",
    "Daz keeps G-funk party alive — guitar funk and synth leads in sunset pocket.",
    "G-funk laid-back grid, funk guitar syncopation.",
    "Funk guitar loops, synth leads, minor party keys.",
    "Guitar intro, groove sustain, hook via synth or vocal.",
    "G-funk guitar loop with West Coast pocket. Avoid copying Dogg Pound specific loops.",
    "Daz G-funk on highlife guitar patterns."
  ),
  entry(
    "PDNA-000077",
    "Soopafly",
    "West Coast G-funk",
    "Snoop-era glide, synth leads, smooth gangsta funk",
    "Long Beach, California",
    "Doggystyle era, West Coast",
    ["hip-hop", "G-funk", "west coast"],
    "Smooth G-funk glide, Snoop-era synth leads, and gangsta funk elegance.",
    "Soopafly makes menace glide — funk is smooth even when lyrics are not.",
    "Ultra-laid-back G-funk, lazy hats, deep kick.",
    "Synth leads, funk chords, whistle hooks.",
    "Smooth intro, groove sustain, synth hook.",
    "Smooth G-funk with synth lead hooks. Avoid copying Doggystyle-era specific sounds.",
    "Soopafly glide on Brazilian funk carioca."
  ),
  entry(
    "PDNA-000078",
    "Johnny J",
    "Los Angeles Tupac era",
    "West Coast soul, emotional rap orchestration, 90s LA warmth",
    "Los Angeles, California",
    "Death Row, Tupac era",
    ["hip-hop", "west coast", "soul"],
    "Emotional West Coast soul, orchestral rap, and 90s LA warmth.",
    "Johnny J scores rap like film — strings and soul carry grief and ambition.",
    "West Coast mid-tempo, soul drum feel, emotional pacing.",
    "Soul samples, string arrangements, gospel chord movement.",
    "Intro sample or strings, verse, emotional chorus lift.",
    "Emotional West Coast soul beat with string or sample warmth. Avoid copying 2Pac-era specific beats.",
    "Johnny J orchestration on trap hi-hat rolls."
  ),
  entry(
    "PDNA-000079",
    "Sam Snead",
    "Bay Area hyphy precursor",
    "Bay Area bounce, trunk funk, Northern California party",
    "Oakland, California",
    "Bay Area hip-hop",
    ["hip-hop", "bay area", "hyphy"],
    "Bay Area bounce, trunk funk, and Northern California party energy.",
    "Bay Area beats prioritize trunk physics — if the car doesn't shake, the mix isn't done.",
    "Bouncy kick patterns, clap accents, uptempo party grid.",
    "Funk synths, simple hooks, major key energy.",
    "Party intro, bounce sustain, chant hook.",
    "Bay Area bounce beat with trunk-ready low end. Avoid copying specific Bay Area classics.",
    "Bay bounce on UK grime snare patterns."
  ),
  entry(
    "PDNA-000080",
    "Ant Banks",
    "Bay Area/Oakland",
    "Oakland funk-rap, Conscious Daughters era, Northern California grit",
    "Oakland, California",
    "Bay Area, Oakland hip-hop",
    ["hip-hop", "bay area", "funk"],
    "Oakland funk-rap, Northern California grit, and trunk-ready funk loops.",
    "Ant Banks defines Oakland sound — funk is political and party simultaneously.",
    "Funk break beats, Oakland bounce influence, hard clap.",
    "Funk loops, minor key street narratives.",
    "Funk intro, verse loop, hook via sample.",
    "Oakland funk-rap with trunk-ready drums. Avoid copying Ant Banks' specific funk flips.",
    "Ant Banks Oakland funk on amapiano groove."
  )
];
