/**
 * Batch 001 seed candidates — 50 global foundation producers.
 * Each entry includes verified-metadata stubs and analytical DNA capsules.
 */

export interface Batch001SeedEntry {
  id: string;
  name: string;
  regionScene: string;
  coreDnaAngle: string;
  country?: string;
  region?: string;
  primaryGenres: string[];
  sceneMovement: string;
  signatureSoundSummary: string;
  artisticDna: string;
  technicalDna: string;
  rhythmicDna: string;
  melodicHarmonicDna: string;
  arrangementDna: string;
  typeBeatInspiredDirection: string;
  originalityTwist: string;
  researchConfidence: string;
}

export const BATCH_001_SEED: Batch001SeedEntry[] = [
  {
    id: "PDNA-000001",
    name: "George Martin",
    regionScene: "UK pop/rock studio era",
    coreDnaAngle: "Arrangement-as-production, orchestral pop architecture, studio imagination",
    country: "United Kingdom",
    region: "London",
    primaryGenres: ["pop", "rock", "orchestral pop"],
    sceneMovement: "British Invasion studio production",
    signatureSoundSummary:
      "Orchestral layering, playful studio experimentation, and arrangement that defines the song as much as performance.",
    artisticDna:
      "Martin treats the studio as a compositional canvas — string beds, tape effects, and sectional drama become the emotional architecture of pop.",
    technicalDna:
      "Verified tools require per-source research. Audible analysis suggests meticulous multitrack orchestration, varispeed experimentation, and classical arrangement discipline.",
    rhythmicDna: "Straight pop/rock grids with orchestral punctuation; rhythm serves narrative arc over groove obsession.",
    melodicHarmonicDna: "Sophisticated chord movement, Beatles-era modal color, orchestral voicings that widen pop harmony.",
    arrangementDna: "Intro hooks, sectional contrast, orchestral swells, and fade dynamics that teach pop structure.",
    typeBeatInspiredDirection:
      "Orchestral-pop beat with layered strings, playful studio FX, and arrangement-first hooks. Avoid copying specific Beatles melodies or trademark intros.",
    originalityTwist: "Combine Martin-like sectional orchestration with modern trap hi-hat language or amapiano log-drum bounce.",
    researchConfidence: "Mixed: historical facts need citation; audible analysis marked D-tier."
  },
  {
    id: "PDNA-000002",
    name: "Phil Spector",
    regionScene: "US pop",
    coreDnaAngle: "Dense mono drama, layered percussion, wall arrangement thinking",
    country: "United States",
    region: "Los Angeles",
    primaryGenres: ["pop", "rock", "girl group"],
    sceneMovement: "Wall of Sound era",
    signatureSoundSummary: "Mono density, stacked percussion, reverberant drama, and maximal emotional impact in narrow bandwidth.",
    artisticDna: "Spector's logic is cinematic compression — many instruments become one voice, emotion through thickness not space.",
    technicalDna: "Verified gear requires citation. Audible analysis suggests heavy room reverb, layered overdubs, and mono summing as aesthetic choice.",
    rhythmicDna: "Tambourine-forward pulse, stacked drums, wall-of-percussion that blurs attack transients.",
    melodicHarmonicDna: "Simple hooks buried in harmonic density; sweetness through texture more than complexity.",
    arrangementDna: "Build-to-climax arcs, intro-as-statement, and drop-ins of full ensemble.",
    typeBeatInspiredDirection:
      "Dense mono-pop production with stacked percussion and reverb drama. Avoid copying Ronettes/Righteous Brothers arrangements.",
    originalityTwist: "Apply wall-of-sound density logic to a single 808 sub and one vocal — hyper-minimal source, maximal layering.",
    researchConfidence: "Mixed: historical facts need citation; audible analysis marked D-tier."
  },
  {
    id: "PDNA-000003",
    name: "Quincy Jones",
    regionScene: "US jazz/R&B/pop",
    coreDnaAngle: "Sophisticated arrangement, groove polish, elite collaborator architecture",
    country: "United States",
    region: "Los Angeles",
    primaryGenres: ["jazz", "R&B", "pop", "funk"],
    sceneMovement: "Crossover studio excellence",
    signatureSoundSummary: "Polished groove, jazz-harmonic sophistication, and A-list session architecture.",
    artisticDna: "Jones orchestrates talent — the production is a system of elite performances locked into irresistible pocket.",
    technicalDna: "Verified credits extensive; audible analysis suggests tight rhythm section capture, horn section voicing, and mix clarity.",
    rhythmicDna: "Funk-jazz pocket, live drummer authority, syncopated bass conversation.",
    melodicHarmonicDna: "Jazz extensions in pop context, sophisticated voicings, memorable top-line hooks.",
    arrangementDna: "Sectional builds, horn stabs, string pads, and dynamic vocal showcases.",
    typeBeatInspiredDirection:
      "Polished live-session groove with horn stabs and sophisticated chords. Avoid copying Thriller-era exact arrangements.",
    originalityTwist: "Jones-level session architecture applied to a single-producer DAW workflow with virtual horn sections.",
    researchConfidence: "Mixed: many Tier A/B credits available; analysis D-tier."
  },
  {
    id: "PDNA-000004",
    name: "Brian Eno",
    regionScene: "UK art rock/ambient",
    coreDnaAngle: "Systems, atmosphere, generative texture, emotional minimalism",
    country: "United Kingdom",
    region: "London",
    primaryGenres: ["ambient", "art rock", "electronic", "experimental"],
    sceneMovement: "Ambient invention, generative systems",
    signatureSoundSummary: "Atmospheric beds, oblique strategies, texture-as-composition, and emotional restraint.",
    artisticDna: "Eno designs environments for feeling — the listener completes the music inside suggested space.",
    technicalDna: "Verified tape/treatment history; audible analysis suggests delay loops, tape saturation, and generative rule systems.",
    rhythmicDna: "Often arrhythmic or pulse-subtle; when present, motorik or loose human drift.",
    melodicHarmonicDna: "Modal stasis, slow harmonic drift, consonance with occasional dissonant color.",
    arrangementDna: "Slow evolution, subtractive arrangement, and foreground/background role reversals.",
    typeBeatInspiredDirection:
      "Ambient texture bed with slow evolution and oblique melodic gestures. Avoid copying Music for Airports harmonic cells.",
    originalityTwist: "Eno-like generative rules driving trap drum randomization or footwork chop density.",
    researchConfidence: "Mixed: extensive interviews for Tier A process claims; sonic analysis D-tier."
  },
  {
    id: "PDNA-000005",
    name: 'Lee "Scratch" Perry',
    regionScene: "Jamaica dub/reggae",
    coreDnaAngle: "Studio-as-instrument, dub weirdness, spiritual distortion, tape surrealism",
    country: "Jamaica",
    region: "Kingston",
    primaryGenres: ["reggae", "dub", "roots"],
    sceneMovement: "Black Ark dub experimentation",
    signatureSoundSummary: "Dub space, spiritual FX, vocal throws, and tape-as-mysticism.",
    artisticDna: "Perry hears the mixing desk as oracle — deletion, echo, and distortion are theological decisions.",
    technicalDna: "Verified Black Ark lore; audible analysis suggests send/return dub techniques, tape manipulation, and radical EQ.",
    rhythmicDna: "One-drop foundation with dub space carved from drums and bass.",
    melodicHarmonicDna: "Roots simplicity with psychedelic modulation via effects.",
    arrangementDna: "Strip-to-nothing breakdowns, vocal disappearance, and surprise FX entrances.",
    typeBeatInspiredDirection:
      "Dub-space production with heavy sends and psychedelic tape texture. Avoid copying specific Perry riddims.",
    originalityTwist: "Perry-style dub throws on a modern hyperpop vocal chain or drill 808 sub.",
    researchConfidence: "Mixed: oral history rich; primary citations needed per claim."
  },
  {
    id: "PDNA-000006",
    name: "King Tubby",
    regionScene: "Jamaica dub",
    coreDnaAngle: "Mixer-as-composer, space, delay throws, bass-and-drum architecture",
    country: "Jamaica",
    region: "Kingston",
    primaryGenres: ["dub", "reggae", "roots"],
    sceneMovement: "King Tubby's Home Town dub",
    signatureSoundSummary: "Bass-forward space, delay throws, drum-and-bass isolation, and mixer-as-composer logic.",
    artisticDna: "Tubby sculpts time — echo feedback and bass weight define the emotional physics of the track.",
    technicalDna: "Verified mixing-desk innovation history; audible analysis suggests spring reverb, analog delay, and radical stem muting.",
    rhythmicDna: "Rocksteady/one-drop with space carved by mute and echo.",
    melodicHarmonicDna: "Minimal harmonic movement; melody often delegated to bass or occasional keyboard.",
    arrangementDna: "Version logic — same riddim, new spatial story each mix.",
    typeBeatInspiredDirection:
      "Dub mix with isolated bass/drum focus and delay throws. Avoid copying Tubby's specific King Tubby Presents mixes.",
    originalityTwist: "Tubby-style stem isolation on a lo-fi house loop or amapiano piano pattern.",
    researchConfidence: "Mixed: foundational dub history well-documented; per-track claims need citation."
  },
  {
    id: "PDNA-000007",
    name: "Giorgio Moroder",
    regionScene: "Italy/Germany disco/electronic",
    coreDnaAngle: "Sequenced propulsion, synth disco, machine sensuality",
    country: "Italy",
    region: "Munich",
    primaryGenres: ["disco", "electronic", "synthpop"],
    sceneMovement: "Munich Machine, synth disco",
    signatureSoundSummary: "Sequenced arpeggios, four-on-the-floor drive, and machine-human sensuality.",
    artisticDna: "Moroder makes the sequencer breathe erotically — repetition becomes hypnosis not boredom.",
    technicalDna: "Verified Moog/sequencer history; audible analysis suggests arpeggiated bass, gated pads, and tight drum machine grid.",
    rhythmicDna: "Four-on-the-floor precision, hi-hat 16ths, disco kick authority.",
    melodicHarmonicDna: "Minor-key disco melancholy, arpeggio hooks, simple chord cycles.",
    arrangementDna: "Slow filter opens, layer-add builds, and extended dancefloor arcs.",
    typeBeatInspiredDirection:
      "Sequenced disco-electronic with arpeggiated bass and gated synths. Avoid copying Moroder's exact I Feel Love patterns.",
    originalityTwist: "Moroder propulsion with dembow kick syncopation or Afrobeats percussion layer.",
    researchConfidence: "Mixed: gear history well-known; per-production citations needed."
  },
  {
    id: "PDNA-000008",
    name: "Tom Dowd",
    regionScene: "US soul/rock/jazz",
    coreDnaAngle: "Engineering innovation, live feel, multitrack clarity",
    country: "United States",
    region: "Miami / New York",
    primaryGenres: ["soul", "rock", "jazz", "R&B"],
    sceneMovement: "Atlantic Records engineering era",
    signatureSoundSummary: "Clean multitrack capture, live room energy, and engineering that serves performance.",
    artisticDna: "Dowd's genius is invisible clarity — the band feels live while multitrack control enables polish.",
    technicalDna: "Verified eight-track innovation; audible analysis suggests natural room ambience and minimal over-processing.",
    rhythmicDna: "Live drummer pocket, soul shuffle, rock straight-time versatility.",
    melodicHarmonicDna: "Performance-first; harmony captured not constructed.",
    arrangementDna: "Documentary capture with subtle studio enhancement.",
    typeBeatInspiredDirection:
      "Live-room soul/rock capture aesthetic with natural ambience. Avoid copying specific Atlantic session arrangements.",
    originalityTwist: "Dowd clarity principles applied to a fully programmed beat with simulated room mics.",
    researchConfidence: "Mixed: engineering history strong; per-session claims need citation."
  },
  {
    id: "PDNA-000009",
    name: "Teo Macero",
    regionScene: "US jazz",
    coreDnaAngle: "Tape editing, jazz architecture, post-performance composition",
    country: "United States",
    region: "New York",
    primaryGenres: ["jazz", "fusion", "experimental"],
    sceneMovement: "Columbia jazz editing era",
    signatureSoundSummary: "Tape-spliced jazz suites, post-performance composition, and radical edit logic.",
    artisticDna: "Macero edits performance into new form — the splice is the composition.",
    technicalDna: "Verified tape editing on Miles sessions; audible analysis suggests abrupt cuts, looped sections, and collage structure.",
    rhythmicDna: "Live jazz pulse fragmented by editorial decisions.",
    melodicHarmonicDna: "Modal jazz language recontextualized through tape collage.",
    arrangementDna: "Non-linear suites, sudden genre shifts, and repeated motifs via tape loop.",
    typeBeatInspiredDirection:
      "Tape-edit collage structure with jazz harmonic language. Avoid copying Bitches Brew edit maps.",
    originalityTwist: "Macero-style DAW edits on a trap beat — splice 8-bar sections from different sessions.",
    researchConfidence: "Mixed: Miles collaborations documented; edit specifics need primary sources."
  },
  {
    id: "PDNA-000010",
    name: "Sylvia Robinson",
    regionScene: "US soul/early hip-hop",
    coreDnaAngle: "Label vision, early rap record architecture, commercial bridge-building",
    country: "United States",
    region: "New Jersey",
    primaryGenres: ["soul", "hip-hop", "funk"],
    sceneMovement: "Sugar Hill Records, early rap commercialization",
    signatureSoundSummary: "Commercial rap architecture, label vision, and bridge from soul to hip-hop.",
    artisticDna: "Robinson hears market and culture simultaneously — she architects the first rap hits as products and movements.",
    technicalDna: "Verified Sugar Hill history; audible analysis suggests live band + rap vocal integration.",
    rhythmicDna: "Funk pocket underpinning early rap cadence.",
    melodicHarmonicDna: "Soul chord loops supporting rhythmic vocal delivery.",
    arrangementDna: "Hook-forward rap structure, band breakdowns, and party-ready dynamics.",
    typeBeatInspiredDirection:
      "Live-band funk underpinning rhythmic vocal delivery. Avoid copying Rapper's Delight arrangement.",
    originalityTwist: "Robinson bridge-building logic applied to Afrobeats-rap crossover with label-ready hook architecture.",
    researchConfidence: "Mixed: historical role documented; per-credit verification needed."
  },
  {
    id: "PDNA-000011",
    name: "Rick Rubin",
    regionScene: "US hip-hop/rock",
    coreDnaAngle: "Reduction, rawness, cross-genre minimal power",
    country: "United States",
    region: "New York / Los Angeles",
    primaryGenres: ["hip-hop", "rock", "metal", "country"],
    sceneMovement: "Def Jam, American Recordings",
    signatureSoundSummary: "Stripped arrangements, room energy, and genre-agnostic raw power.",
    artisticDna: "Rubin subtracts until truth remains — volume and performance replace production tricks.",
    technicalDna: "Verified minimal-mic philosophy; audible analysis suggests dry vocals, loud drums, and anti-gloss aesthetic.",
    rhythmicDna: "Boom-bap directness or live rock pulse; no excess programming.",
    melodicHarmonicDna: "Song-first; harmony serves vocal narrative.",
    arrangementDna: "Radical subtraction, dynamic contrast through performance not layers.",
    typeBeatInspiredDirection:
      "Stripped raw beat with room energy and minimal layers. Avoid copying LL Cool J or Slayer production fingerprints.",
    originalityTwist: "Rubin reduction applied to hyperpop — one synth, one vocal, extreme loudness discipline.",
    researchConfidence: "Mixed: philosophy well-interviewed; per-track claims need citation."
  },
  {
    id: "PDNA-000012",
    name: "Dr. Dre",
    regionScene: "US West Coast hip-hop",
    coreDnaAngle: "Low-end authority, polished menace, vocal pocket control",
    country: "United States",
    region: "Los Angeles / Compton",
    primaryGenres: ["hip-hop", "G-funk", "rap"],
    sceneMovement: "G-funk, Aftermath",
    signatureSoundSummary: "Lush low end, whistling synths, polished menace, and vocal pocket mastery.",
    artisticDna: "Dre sells cinematic California menace through clean mix hierarchy — kick, bass, and vocal own the frame.",
    technicalDna: "Verified MPC/live musician hybrid history; audible analysis suggests deep 808/sub, crisp snare, and synth lead hooks.",
    rhythmicDna: "Laid-back West Coast swing, lazy hi-hats, authoritative kick.",
    melodicHarmonicDna: "Funk sample loops, minor-key menace, whistling lead motifs.",
    arrangementDna: "Intro hook statement, verse pocket, chorus lift via synth or strings.",
    typeBeatInspiredDirection:
      "West Coast G-funk with deep low end and lazy swing. Avoid copying Chronic/2001 exact drum patterns or synth leads.",
    originalityTwist: "Dre low-end authority with UK drill hi-hat patterns or Brazilian funk tamborzão.",
    researchConfidence: "Mixed: extensive catalogue; per-track sample credits need verification."
  },
  {
    id: "PDNA-000013",
    name: "J Dilla",
    regionScene: "Detroit hip-hop",
    coreDnaAngle: "Humanized swing, asymmetry, emotional imperfection",
    country: "United States",
    region: "Detroit",
    primaryGenres: ["hip-hop", "neo-soul", "underground rap"],
    sceneMovement: "Detroit beat scene, Soulquarians-adjacent production culture",
    signatureSoundSummary:
      "Off-grid drum feel, warm sample loops, chopped soul/jazz fragments, emotionally human imperfection.",
    artisticDna:
      "Dilla's deeper logic is not just swing — it is the feeling that the machine is breathing. Beats feel bent, intimate, warm, and conversational.",
    technicalDna:
      "Verified tools must be researched per source. Audible analysis suggests sampler-centered construction, non-rigid quantization, warm low-mid texture, and loop transformation.",
    rhythmicDna: "Loose kicks, late snares, swung hats, and microtiming that feels human rather than sloppy.",
    melodicHarmonicDna: "Soul/jazz/gospel fragments, short motifs, bittersweet chord color, unresolved emotional loops.",
    arrangementDna: "Often loop-based, but replay value comes from pocket, texture, chops, drops, and subtle variation.",
    typeBeatInspiredDirection:
      "Warm sample-based beat with humanized swing, understated bass, dusty drums, and emotional loop repetition. Avoid copying exact drum timing, sample choices, or recognizable chop patterns.",
    originalityTwist:
      "Combine Dilla-like humanized rhythm logic with New Orleans bounce percussion, ambient pads, or modern melodic rap space.",
    researchConfidence: "Mixed: historical facts need citation; audible analysis marked D-tier."
  },
  {
    id: "PDNA-000014",
    name: "DJ Premier",
    regionScene: "New York boom bap",
    coreDnaAngle: "Chopped grit, scratched hooks, drum-loop authority",
    country: "United States",
    region: "New York",
    primaryGenres: ["hip-hop", "boom bap"],
    sceneMovement: "Gang Starr, East Coast golden era",
    signatureSoundSummary: "Hard drums, scratched hooks, chopped soul/jazz samples, and boom-bap authority.",
    artisticDna: "Premier makes drums the personality — scratches are hooks, samples are brief punches not wallpapers.",
    technicalDna: "Verified SP-1200/sampler history; audible analysis suggests crisp kick/snare, filtered sample chops, and turntable hook integration.",
    rhythmicDna: "Hard snare, steady kick, boom-bap grid with sample-chop punctuation.",
    melodicHarmonicDna: "Short soul/jazz loops, minor key grit, horn stabs.",
    arrangementDna: "Scratch hook intro, verse loop, minimal variation, outro scratch.",
    typeBeatInspiredDirection:
      "Boom-bap with hard drums and scratch-ready hook space. Avoid copying Premier's exact Gang Starr drum samples.",
    originalityTwist: "Premier drum authority with Latin percussion or amapiano piano counter-rhythm.",
    researchConfidence: "Mixed: catalogue vast; sample sources need per-track citation."
  },
  {
    id: "PDNA-000015",
    name: "RZA",
    regionScene: "Staten Island/Wu-Tang",
    coreDnaAngle: "Dusty soul, martial arts cinema, raw texture, minor-key mythology",
    country: "United States",
    region: "Staten Island",
    primaryGenres: ["hip-hop", "boom bap", "experimental rap"],
    sceneMovement: "Wu-Tang Clan production",
    signatureSoundSummary: "Dusty loops, minor-key tension, kung-fu samples, and raw SP-1200 grit.",
    artisticDna: "RZA builds mythology through dirt — cheap sampler texture becomes cinematic gravity.",
    technicalDna: "Verified SP-1200 era; audible analysis suggests dirty compression, soul loop pitch-down, and dialogue samples.",
    rhythmicDna: "Off-kilter drums, loose timing, snare urgency.",
    melodicHarmonicDna: "Minor soul loops, cinematic strings, dark chord stasis.",
    arrangementDna: "Skits as structure, sudden beat switches, clan posse energy.",
    typeBeatInspiredDirection:
      "Dusty minor-key loop with cinematic sample space and raw drums. Avoid copying 36 Chambers specific loops.",
    originalityTwist: "RZA dirt applied to clean hyperpop synths — intentional bit-crush on glossy sounds.",
    researchConfidence: "Mixed: Wu history documented; per-sample clearance unknown."
  },
  {
    id: "PDNA-000016",
    name: "Timbaland",
    regionScene: "Virginia hip-hop/R&B/pop",
    coreDnaAngle: "Percussive futurism, negative space, vocal rhythm as drum language",
    country: "United States",
    region: "Virginia Beach",
    primaryGenres: ["hip-hop", "R&B", "pop"],
    sceneMovement: "Virginia production, Missy Elliott partnership",
    signatureSoundSummary: "Percussive synths, negative space, bouncy irregularity, and vocal rhythm as percussion.",
    artisticDna: "Timbaland makes silence bounce — drums and vocals share the grid as one rhythmic instrument.",
    technicalDna: "Verified drum machine/synth hybrid; audible analysis suggests dry punchy drums, quirky synth bleeps, and space between hits.",
    rhythmicDna: "Syncopated bounce, missing-kick patterns, percussive vocal interplay.",
    melodicHarmonicDna: "Minimal harmonic movement, hook-centric top lines, Eastern scale color at times.",
    arrangementDna: "Drop-out sections, beat-switch bridges, and percussive breakdowns.",
    typeBeatInspiredDirection:
      "Bouncy percussive beat with negative space and quirky synth accents. Avoid copying Get Ur Freak On drum syntax.",
    originalityTwist: "Timbaland bounce with Brazilian baile funk rhythm or Indian tabla patterns.",
    researchConfidence: "Mixed: hit catalogue well-known; per-track credits need verification."
  },
  {
    id: "PDNA-000017",
    name: "The Neptunes",
    regionScene: "Virginia pop/rap/R&B",
    coreDnaAngle: "Sparse bounce, synthetic funk, weird minimal hooks",
    country: "United States",
    region: "Virginia Beach",
    primaryGenres: ["hip-hop", "pop", "R&B"],
    sceneMovement: "Virginia production duo (Pharrell & Chad Hugo)",
    signatureSoundSummary: "Sparse bounce, clap-heavy drums, weird minimal hooks, and synthetic funk.",
    artisticDna: "The Neptunes make oddity catchy — two or three sounds carry the entire song's personality.",
    technicalDna: "Verified synth/drum machine palette; audible analysis suggests dry drums, simple synth chords, and unconventional sound choices.",
    rhythmicDna: "Bouncy sparse grids, clap on unexpected beats, kick minimalism.",
    melodicHarmonicDna: "Simple chord stabs, quirky intervals, hook-first simplicity.",
    arrangementDna: "Ultra-minimal layers, sudden stops, and hook repetition.",
    typeBeatInspiredDirection:
      "Sparse bouncy beat with weird synth hook and clap-heavy drums. Avoid copying Happy or Grindin patterns.",
    originalityTwist: "Neptunes sparsity with orchestral stabs or drill 808 sub underneath minimal top layer.",
    researchConfidence: "Mixed: production identity clear; per-track citations needed."
  },
  {
    id: "PDNA-000018",
    name: "Missy Elliott",
    regionScene: "Virginia hip-hop/R&B",
    coreDnaAngle: "Vocal-producer imagination, playful futurism, rhythm-first song design",
    country: "United States",
    region: "Virginia Beach",
    primaryGenres: ["hip-hop", "R&B", "pop"],
    sceneMovement: "Timbaland/Missy creative partnership",
    signatureSoundSummary: "Playful futurism, vocal-as-instrument design, and rhythm-first song architecture.",
    artisticDna: "Missy produces personality — vocal effects, ad-libs, and rhythmic delivery are arranged like drum fills.",
    technicalDna: "Co-production with Timbaland documented; audible analysis suggests vocal FX chains, punchy drums, and experimental sound design.",
    rhythmicDna: "Hiccup vocals, stop-start patterns, percussive delivery.",
    melodicHarmonicDna: "Hook-centric, often simple harmony with bold melodic contour.",
    arrangementDna: "Surprise sections, vocal FX bridges, and playful dropouts.",
    typeBeatInspiredDirection:
      "Playful futuristic beat with vocal-as-percussion space. Avoid copying Missy/Timbaland signature vocal tags.",
    originalityTwist: "Missy vocal-producer logic applied to hyperpop or amapiano vocal chop aesthetics.",
    researchConfidence: "Mixed: co-production credits complex; solo production claims need citation."
  },
  {
    id: "PDNA-000019",
    name: "Metro Boomin",
    regionScene: "Atlanta trap",
    coreDnaAngle: "Dark cinematic trap, negative space, 808 mood architecture",
    country: "United States",
    region: "Atlanta",
    primaryGenres: ["trap", "hip-hop"],
    sceneMovement: "Modern Atlanta trap, cinematic trap",
    signatureSoundSummary: "Dark cinematic pads, rolling hi-hats, 808 slides, and negative space menace.",
    artisticDna: "Metro scores trap like film — atmosphere and 808 are characters, not just rhythm.",
    technicalDna: "Verified FL Studio lineage; audible analysis suggests layered 808s, sparse melodic hooks, and wide reverb tails.",
    rhythmicDna: "Hi-hat rolls, triplet feel, 808 slide punctuation.",
    melodicHarmonicDna: "Minor-key loops, simple two-chord tension, cinematic strings.",
    arrangementDna: "Beat drop architecture, half-time switches, and outro fade on 808.",
    typeBeatInspiredDirection:
      "Dark cinematic trap with 808 mood and sparse melody. Avoid copying Metro's exact 808 slides or tag sounds.",
    originalityTwist: "Metro darkness with Middle Eastern maqam melody or Japanese city pop chord extensions.",
    researchConfidence: "Mixed: modern credits traceable; sonic analysis D-tier."
  },
  {
    id: "PDNA-000020",
    name: "Mike WiLL Made-It",
    regionScene: "Atlanta trap/pop rap",
    coreDnaAngle: "Elastic 808s, hard minimal loops, hook-forward trap design",
    country: "United States",
    region: "Atlanta",
    primaryGenres: ["trap", "pop rap", "hip-hop"],
    sceneMovement: "Atlanta trap-pop crossover",
    signatureSoundSummary: "Elastic 808s, hard minimal loops, and hook-forward trap design.",
    artisticDna: "Mike WiLL makes loops that feel inevitable — one motif carries club and radio simultaneously.",
    technicalDna: "Verified producer tag culture; audible analysis suggests bouncy 808, simple synth loop, and hard clap/snare.",
    rhythmicDna: "Bounce-heavy 808, steady hat patterns, clap authority.",
    melodicHarmonicDna: "Earworm loops, often single-chord or two-chord hypnotic repetition.",
    arrangementDna: "Hook-first, minimal verse variation, tag as branding.",
    typeBeatInspiredDirection:
      "Hook-forward trap loop with elastic 808 bounce. Avoid copying Black Beatles or Mercy patterns.",
    originalityTwist: "Mike WiLL bounce with Afrobeats percussion or dembow kick layer.",
    researchConfidence: "Mixed: credits available on major hits; per-track verification needed."
  },
  {
    id: "PDNA-000021",
    name: "Zaytoven",
    regionScene: "Atlanta trap/gospel",
    coreDnaAngle: "Church chords, loose piano, trap bounce, human touch",
    country: "United States",
    region: "Atlanta",
    primaryGenres: ["trap", "gospel", "hip-hop"],
    sceneMovement: "Atlanta trap piano tradition",
    signatureSoundSummary: "Churchy piano, loose feel, trap drums, and human warmth in machine context.",
    artisticDna: "Zaytoven brings gospel soul to trap — piano is preacher, 808 is congregation.",
    technicalDna: "Verified piano-first production; audible analysis suggests live piano feel, simple trap drum programming.",
    rhythmicDna: "Bouncy trap with slightly loose piano syncopation.",
    melodicHarmonicDna: "Gospel chord voicings, major/minor emotional toggles.",
    arrangementDna: "Piano intro, loop sustain, minimal breaks.",
    typeBeatInspiredDirection:
      "Gospel-piano trap with loose feel and bouncy 808. Avoid copying Zaytoven's exact piano voicings.",
    originalityTwist: "Zaytoven gospel harmony on UK garage shuffled drums.",
    researchConfidence: "Mixed: style well-recognized; formal citations needed."
  },
  {
    id: "PDNA-000022",
    name: "Lex Luger",
    regionScene: "Southern trap",
    coreDnaAngle: "Maximal brass/synth aggression, hard snare energy",
    country: "United States",
    region: "Virginia / Atlanta",
    primaryGenres: ["trap", "hip-hop"],
    sceneMovement: "Lex Luger trap maximalism",
    signatureSoundSummary: "Brass stabs, hard snares, aggressive synth stacks, and maximal trap energy.",
    artisticDna: "Luger turns trap into arena — brass and synth aggression replace subtlety.",
    technicalDna: "Verified Fruity Loops era; audible analysis suggests layered brass, hard snare, and rapid hi-hats.",
    rhythmicDna: "Hard snare crack, fast hats, 808 underpinning.",
    melodicHarmonicDna: "Minor brass stabs, simple synth leads, anthemic hooks.",
    arrangementDna: "Build-drop energy, brass hook statements.",
    typeBeatInspiredDirection:
      "Maximal trap with brass stabs and hard snare. Avoid copying Hard in da Paint or B.M.F. patterns.",
    originalityTwist: "Luger brass aggression with salsa horn section voicings or Bollywood brass.",
    researchConfidence: "Mixed: iconic tracks documented; per-track credits need verification."
  },
  {
    id: "PDNA-000023",
    name: "Southside",
    regionScene: "Atlanta trap",
    coreDnaAngle: "Dark drum programming, high-energy 808 pressure",
    country: "United States",
    region: "Atlanta",
    primaryGenres: ["trap", "hip-hop"],
    sceneMovement: "808 Mafia, modern Atlanta trap",
    signatureSoundSummary: "Dark aggressive drums, high-energy 808 pressure, and relentless trap momentum.",
    artisticDna: "Southside pushes trap into athletic intensity — drums feel like combat.",
    technicalDna: "Verified 808 Mafia lineage; audible analysis suggests distorted 808, rapid hats, and dark synth atmospheres.",
    rhythmicDna: "Machine-gun hats, hard kick patterns, 808 distortion.",
    melodicHarmonicDna: "Dark minor loops, minimal melody, atmosphere over harmony.",
    arrangementDna: "Energy sustain, few breakdowns, club-first structure.",
    typeBeatInspiredDirection:
      "High-energy dark trap with aggressive 808 and rapid hats. Avoid copying 808 Mafia signature patterns.",
    originalityTwist: "Southside intensity with gabber kick transients or footwork chop rate.",
    researchConfidence: "Mixed: 808 Mafia credits traceable; per-track verification needed."
  },
  {
    id: "PDNA-000024",
    name: "Madlib",
    regionScene: "California underground hip-hop",
    coreDnaAngle: "Crate-digging collage, raw loops, jazz-damaged texture",
    country: "United States",
    region: "Los Angeles / Oxnard",
    primaryGenres: ["hip-hop", "jazz", "experimental"],
    sceneMovement: "Stones Throw, Beat Konducta",
    signatureSoundSummary: "Crate-digging collage, raw loops, jazz-damaged texture, and alter-ego universes.",
    artisticDna: "Madlib treats records as infinite — every loop is a portal, every alias a new world.",
    technicalDna: "Verified MPC/crate-dig culture; audible analysis suggests unpolished loops, vinyl texture, and abrupt edits.",
    rhythmicDna: "Loose drums, off-grid feel, loop repetition with micro-variation.",
    melodicHarmonicDna: "Obscure jazz/soul/funk samples, modal color, unexpected key centers.",
    arrangementDna: "Short loops, skit interruptions, mixtape logic.",
    typeBeatInspiredDirection:
      "Raw crate-dig loop collage with jazz-damaged texture. Avoid copying Madlib's specific sample flips.",
    originalityTwist: "Madlib collage logic with field recordings from non-Western musical traditions.",
    researchConfidence: "Mixed: sample sources often obscure; clearance status frequently unknown."
  },
  {
    id: "PDNA-000025",
    name: "Pete Rock",
    regionScene: "New York hip-hop",
    coreDnaAngle: "Warm horn loops, soul-jazz chops, head-nod elegance",
    country: "United States",
    region: "New York",
    primaryGenres: ["hip-hop", "boom bap", "soul"],
    sceneMovement: "Pete Rock & CL Smooth, golden era",
    signatureSoundSummary: "Warm horn loops, soul-jazz chops, head-nod elegance, and filtered sample warmth.",
    artisticDna: "Pete Rock makes nostalgia warm — horns sigh, drums nod, samples feel like memory.",
    technicalDna: "Verified SP-1200/MPC era; audible analysis suggests filtered soul samples, horn overlays, and crisp drums.",
    rhythmicDna: "Head-nod swing, laid-back kick/snare, boom-bap grace.",
    melodicHarmonicDna: "Soul-jazz loops, major/minor warmth, horn melody integration.",
    arrangementDna: "Loop evolution via filter opens, horn entrance, outro fade.",
    typeBeatInspiredDirection:
      "Warm soul-jazz chop with horn accents and head-nod drums. Avoid copying T.R.O.Y. or They Reminisce loops.",
    originalityTwist: "Pete Rock warmth with Nordic jazz harmony or Brazilian bossa sample logic.",
    researchConfidence: "Mixed: sample-based catalogue; per-track sources need citation."
  },
  {
    id: "PDNA-000026",
    name: "Marley Marl",
    regionScene: "Queensbridge hip-hop",
    coreDnaAngle: "Sampling architecture, drum reconstruction, early beat science",
    country: "United States",
    region: "Queens, New York",
    primaryGenres: ["hip-hop", "boom bap"],
    sceneMovement: "Juice Crew, Cold Chillin'",
    signatureSoundSummary: "Drum reconstruction, sample layering, and foundational beat science.",
    artisticDna: "Marley Marl invents the modern beat — separating and recombining drum breaks is production itself.",
    technicalDna: "Verified sampling innovation history; audible analysis suggests layered breaks, punchy drum composites.",
    rhythmicDna: "Composite break science, punchy kick/snare from multiple sources.",
    melodicHarmonicDna: "Sample loops with horn/string soul color.",
    arrangementDna: "Classic verse-chorus loop, DJ-friendly structure.",
    typeBeatInspiredDirection:
      "Composite drum break beat with layered sample loops. Avoid copying Marley Marl's exact break combinations.",
    originalityTwist: "Marley break-composite logic applied to live-recorded drum takes instead of samples.",
    researchConfidence: "Mixed: foundational history documented; per-track break sources need citation."
  },
  {
    id: "PDNA-000027",
    name: "DJ Screw",
    regionScene: "Houston",
    coreDnaAngle: "Slowed time, syrup atmosphere, remix-as-worldbuilding",
    country: "United States",
    region: "Houston",
    primaryGenres: ["hip-hop", "chopped and screwed"],
    sceneMovement: "Houston chopped and screwed",
    signatureSoundSummary: "Slowed pitch-down, chopped verses, syrup atmosphere, and remix-as-worldbuilding.",
    artisticDna: "Screw bends time until reality melts — the remix is a new dimension, not a variation.",
    technicalDna: "Verified turntable pitch/slow technique; audible analysis suggests pitched-down vocals, loose timing, and hazy texture.",
    rhythmicDna: "Half-time or slower, dragged snare, submerged kick.",
    melodicHarmonicDna: "Pitch-shifted sample harmony, darker tonal center from slowdown.",
    arrangementDna: "Chopped verse repeats, freestyle overlays, mixtape continuity.",
    typeBeatInspiredDirection:
      "Slowed hazy beat with pitch-shifted atmosphere. Avoid copying Screw's specific chop patterns on known tracks.",
    originalityTwist: "Screw slowdown on amapiano or dembow — regional rhythm at sub-tempo.",
    researchConfidence: "Mixed: technique well-documented; per-mixtape track lists need citation."
  },
  {
    id: "PDNA-000028",
    name: "SOPHIE",
    regionScene: "UK/Scotland hyperpop/electronic",
    coreDnaAngle: "Plastic-metal sound design, extreme synthetic physicality",
    country: "United Kingdom",
    region: "Glasgow / London",
    primaryGenres: ["hyperpop", "electronic", "experimental pop"],
    sceneMovement: "PC Music, hyperpop",
    signatureSoundSummary: "Plastic-metal synths, extreme transients, synthetic physicality, and bubble-pop aggression.",
    artisticDna: "SOPHIE makes sound feel tactile — synthesis as material science, pop as sculpture.",
    technicalDna: "Verified synthesis-focused production; audible analysis suggests sharp transients, metallic timbres, and pitch-shifted vocals.",
    rhythmicDna: "Sharp drum design, irregular accents, percussive synth stabs.",
    melodicHarmonicDna: "Bright dissonance, bubblegum hooks, unexpected chord colors.",
    arrangementDna: "Sudden timbral shifts, drop impact via sound design not arrangement.",
    typeBeatInspiredDirection:
      "Hyper-synthetic beat with metallic transients and plastic texture. Avoid copying SOPHIE's exact Lemonade/Immaterial sound design.",
    originalityTwist: "SOPHIE synthetic physicality on acoustic instruments — processed tabla or kora.",
    researchConfidence: "Mixed: interviews available; specific synthesis chains D-tier."
  },
  {
    id: "PDNA-000029",
    name: "Arca",
    regionScene: "Venezuela/global experimental pop",
    coreDnaAngle: "Mutant sound design, body-horror beauty, fractured rhythm",
    country: "Venezuela",
    region: "Caracas / global",
    primaryGenres: ["experimental", "electronic", "pop", "industrial"],
    sceneMovement: "Experimental electronic, avant-pop",
    signatureSoundSummary: "Fractured rhythm, mutant sound design, body-horror beauty, and unstable structure.",
    artisticDna: "Arca embraces instability — beauty emerges from digital fracture and rhythmic collapse.",
    technicalDna: "Verified digital production; audible analysis suggests granular synthesis, pitch instability, and deconstructed club rhythms.",
    rhythmicDna: "Broken beats, reggaeton/trap deconstruction, arrhythmic passages.",
    melodicHarmonicDna: "Chromatic wandering, operatic vocals, dissonant beauty.",
    arrangementDna: "Non-linear, sudden resets, collage structure.",
    typeBeatInspiredDirection:
      "Fractured experimental beat with unstable rhythm and mutant texture. Avoid copying Arca's specific KiCk albums sound design.",
    originalityTwist: "Arca fracture logic on traditional folk song structures from Latin America.",
    researchConfidence: "Mixed: artistic statements in interviews; sonic analysis D-tier."
  },
  {
    id: "PDNA-000030",
    name: "Burial",
    regionScene: "UK garage/dubstep",
    coreDnaAngle: "Ghostly urban ambience, shuffled drums, emotional decay",
    country: "United Kingdom",
    region: "London",
    primaryGenres: ["UK garage", "dubstep", "ambient", "electronic"],
    sceneMovement: "Late garage, hauntological electronic",
    signatureSoundSummary: "Ghostly ambience, shuffled 2-step, vocal samples as texture, and urban melancholy.",
    artisticDna: "Burial captures lonely city night — reverb is memory, shuffle is heartbeat, vocals are ghosts.",
    technicalDna: "Verified SoundForge production lore; audible analysis suggests sidechain-like pumping, vinyl crackle, and pitched vocal chops.",
    rhythmicDna: "Shuffled 2-step, off-grid hi-hats, sub-bass weight.",
    melodicHarmonicDna: "Minor ambient pads, R&B vocal fragments, unresolved longing.",
    arrangementDna: "Slow evolution, track dissolve endings, minimal hook repetition.",
    typeBeatInspiredDirection:
      "Ghostly 2-step with shuffled drums and ambient vocal texture. Avoid copying Burial's specific Untrue sonic fingerprints.",
    originalityTwist: "Burial hauntology on Latin bolero samples or West African highlife guitar.",
    researchConfidence: "Mixed: rare interviews; sonic identity D-tier analysis."
  },
  {
    id: "PDNA-000031",
    name: "Aphex Twin",
    regionScene: "UK/Ireland IDM",
    coreDnaAngle: "Algorithmic rhythm, alien melody, playful technical extremity",
    country: "United Kingdom",
    region: "Cornwall",
    primaryGenres: ["IDM", "ambient", "techno", "experimental"],
    sceneMovement: "Warp Records, IDM",
    signatureSoundSummary: "Algorithmic drums, alien melodies, acid textures, and playful extremity.",
    artisticDna: "Aphex makes machines seem sentient — complexity feels organic because it is unpredictably human-coded.",
    technicalDna: "Verified custom gear/software; audible analysis suggests complex drum programming, acid lines, and ambient layers.",
    rhythmicDna: "Drill'n'bass complexity, polyrhythm, sudden tempo shifts.",
    melodicHarmonicDna: "Dissonant beauty, piano ambient, acid squelch as melody.",
    arrangementDna: "Sudden genre switches, joke structures, beat-only then melodic sections.",
    typeBeatInspiredDirection:
      "Complex IDM drums with alien melody and acid texture. Avoid copying Selected Ambient Works or Drukqs specific patterns.",
    originalityTwist: "Aphex complexity applied to simple Afrobeats groove — polyrhythmic percussion under one chord.",
    researchConfidence: "Mixed: Richard D. James interviews selective; technical specifics often D-tier."
  },
  {
    id: "PDNA-000032",
    name: "Daft Punk",
    regionScene: "France house/pop",
    coreDnaAngle: "Robotic funk, filter-house memory, vocoder mythology",
    country: "France",
    region: "Paris",
    primaryGenres: ["house", "electronic", "disco", "pop"],
    sceneMovement: "French house, robot mythology",
    signatureSoundSummary: "Filtered disco loops, vocoder vocals, robotic funk, and sidechain pump.",
    artisticDna: "Daft Punk mythologize machines — disco humanity filtered through robot persona.",
    technicalDna: "Verified sampling/live hybrid; audible analysis suggests filter sweeps, sidechain compression, vocoder chains.",
    rhythmicDna: "Four-on-the-floor, funk guitar chop, steady house grid.",
    melodicHarmonicDna: "Disco sample harmony, vocoder melody, simple chord loops.",
    arrangementDna: "Filter build, drop to full groove, bridge breakdown, robot identity.",
    typeBeatInspiredDirection:
      "Filtered disco-house with vocoder space and sidechain pump. Avoid copying Around the World or One More Time.",
    originalityTwist: "Daft Punk robot funk with amapiano log drum or Arabic pop string section.",
    researchConfidence: "Mixed: sample sources documented on some tracks; per-track verification needed."
  },
  {
    id: "PDNA-000033",
    name: "Kraftwerk",
    regionScene: "Germany electronic",
    coreDnaAngle: "Machine minimalism, sequencer logic, electronic-pop foundation",
    country: "Germany",
    region: "Düsseldorf",
    primaryGenres: ["electronic", "synthpop", "techno", "experimental"],
    sceneMovement: "Krautrock to electronic pop",
    signatureSoundSummary: "Sequencer precision, robotic vocals, minimal melody, and machine mythology.",
    artisticDna: "Kraftwerk invent electronic pop identity — humans become diagrams, machines become pop stars.",
    technicalDna: "Verified custom sequencers; audible analysis suggests rigid grid, synthetic drums, vocoder, and minimal harmonic movement.",
    rhythmicDna: "Motorik pulse, electronic percussion, metronomic precision.",
    melodicHarmonicDna: "Minimal motifs, modal loops, vocoder as harmonic element.",
    arrangementDna: "Repetition with micro-variation, concept-album continuity.",
    typeBeatInspiredDirection:
      "Minimal sequencer-driven electronic with robotic vocal space. Avoid copying Autobahn or Trans-Europe Express motifs.",
    originalityTwist: "Kraftwerk machine logic on live African percussion ensemble recordings.",
    researchConfidence: "Mixed: foundational history well-documented; gear specifics need citation."
  },
  {
    id: "PDNA-000034",
    name: "Wendy Carlos",
    regionScene: "US electronic/classical",
    coreDnaAngle: "Synth translation, timbre discipline, electronic orchestration",
    country: "United States",
    region: "New York",
    primaryGenres: ["electronic", "classical", "film score"],
    sceneMovement: "Moog synthesis pioneer",
    signatureSoundSummary: "Synth orchestral translation, timbre discipline, and electronic classical rigor.",
    artisticDna: "Carlos proves synths can carry classical weight — timbre discipline replaces orchestral body.",
    technicalDna: "Verified Moog modular history; audible analysis suggests precise tuning, orchestral voicing on synth.",
    rhythmicDna: "Classical metric regularity or soundtrack pulse.",
    melodicHarmonicDna: "Bach transcriptions, modal color, precise voice leading.",
    arrangementDna: "Orchestral sectional thinking on monophonic/polyphonic synth.",
    typeBeatInspiredDirection:
      "Synth-orchestral arrangement with timbre discipline. Avoid copying Switched-On Bach voicings.",
    originalityTwist: "Carlos timbre discipline on MPE controllers with non-Western scale systems.",
    researchConfidence: "Mixed: pioneering role Tier A/B; per-work analysis D-tier."
  },
  {
    id: "PDNA-000035",
    name: "Ryuichi Sakamoto",
    regionScene: "Japan/global",
    coreDnaAngle: "Elegant harmony, electronic-acoustic fusion, cinematic restraint",
    country: "Japan",
    region: "Tokyo",
    primaryGenres: ["electronic", "classical", "film score", "pop"],
    sceneMovement: "Yellow Magic Orchestra, solo cinematic work",
    signatureSoundSummary: "Elegant harmony, electronic-acoustic fusion, cinematic restraint, and melancholic beauty.",
    artisticDna: "Sakamoto finds beauty in restraint — each note placed with architectural care.",
    technicalDna: "Verified YMO/solo synthesis history; audible analysis suggests piano-synth blend, spacious mix, minimal ornament.",
    rhythmicDna: "Often subdued; when present, electronic pulse or orchestral rubato.",
    melodicHarmonicDna: "Sophisticated voicings, Japanese modal color, melancholic major/minor ambiguity.",
    arrangementDna: "Space as element, slow builds, cinematic arcs.",
    typeBeatInspiredDirection:
      "Cinematic electronic-acoustic blend with elegant harmony and space. Avoid copying Merry Christmas Mr. Lawrence motifs.",
    originalityTwist: "Sakamoto restraint with trap 808 sub as sole rhythmic anchor.",
    researchConfidence: "Mixed: extensive catalogue; per-score citations needed."
  },
  {
    id: "PDNA-000036",
    name: "Yasutaka Nakata",
    regionScene: "Japan J-pop/electro",
    coreDnaAngle: "Glossy synthetic pop, vocal processing, kawaii-futurist precision",
    country: "Japan",
    region: "Osaka / Tokyo",
    primaryGenres: ["J-pop", "electronic", "electropop"],
    sceneMovement: "CAPSULE, Perfume, Kyary Pamyu Pamyu",
    signatureSoundSummary: "Glossy synth pop, pristine vocal processing, kawaii-futurist sheen, and hook precision.",
    artisticDna: "Nakata makes pop hyperreal — everything slightly too perfect, emotionally amplified by synthetic sheen.",
    technicalDna: "Verified J-pop production; audible analysis suggests bright mix, layered synths, pitch-corrected vocals, sidechain clarity.",
    rhythmicDna: "Electro-pop four-on-the-floor or bounce, crisp hats.",
    melodicHarmonicDna: "Major-key hooks, chromatic passing tones, earworm top lines.",
    arrangementDna: "Intro hook, chorus lift, bridge breakdown, polished outro.",
    typeBeatInspiredDirection:
      "Glossy electropop with pristine vocal processing and hook precision. Avoid copying Perfume/Kyary exact melodies.",
    originalityTwist: "Nakata gloss on lo-fi bedroom pop — intentional contrast of pristine and dusty.",
    researchConfidence: "Mixed: production role clear on major acts; per-track credits need verification."
  },
  {
    id: "PDNA-000037",
    name: "A. R. Rahman",
    regionScene: "India film/pop",
    coreDnaAngle: "Orchestral-electronic fusion, spiritual melody, cinematic scale",
    country: "India",
    region: "Chennai",
    primaryGenres: ["film score", "Indian pop", "world fusion"],
    sceneMovement: "Tamil/Bollywood film music revolution",
    signatureSoundSummary: "Orchestral-electronic fusion, spiritual melody, cinematic scale, and rhythmic diversity.",
    artisticDna: "Rahman fuses sacred and modern — electronics carry spiritual weight at blockbuster scale.",
    technicalDna: "Verified studio/orchestra hybrid; audible analysis suggests layered percussion, synth pads, orchestral swells.",
    rhythmicDna: "Indian rhythmic cycles, electronic pulse, hybrid percussion layers.",
    melodicHarmonicDna: "Raga-influenced melody, orchestral harmony, memorable vocal lines.",
    arrangementDna: "Cinematic builds, choral swells, percussion breakdowns.",
    typeBeatInspiredDirection:
      "Orchestral-electronic fusion with Indian rhythmic color and spiritual melody. Avoid copying Slumdog or Roja themes.",
    originalityTwist: "Rahman scale on intimate single-room production — one vocalist, one synth, cinematic intent.",
    researchConfidence: "Mixed: film credits extensive; per-composition citations needed."
  },
  {
    id: "PDNA-000038",
    name: "Max Martin",
    regionScene: "Sweden pop",
    coreDnaAngle: "Hook architecture, melodic math, chorus engineering",
    country: "Sweden",
    region: "Stockholm",
    primaryGenres: ["pop", "dance-pop", "R&B"],
    sceneMovement: "Cheiron Studio, Swedish pop machine",
    signatureSoundSummary: "Melodic math, chorus lift, hook density, and pop structure engineering.",
    artisticDna: "Max Martin engineers emotion through melody — chorus is destination, verse is runway.",
    technicalDna: "Verified songwriter-producer system; audible analysis suggests layered vocals, bright mix, kick/snare pop punch.",
    rhythmicDna: "Straight pop grid, four-on-the-floor or mid-tempo bounce.",
    melodicHarmonicDna: "Melodic math, surprising chord turns in simple frameworks.",
    arrangementDna: "Pre-chorus lift, chorus impact, post-chorus hook, bridge modulation.",
    typeBeatInspiredDirection:
      "Hook-engineered pop with chorus lift and melodic math. Avoid copying ...Baby One More Time or Blank Space formulas.",
    originalityTwist: "Max Martin chorus engineering on Afrobeats groove or drill tempo.",
    researchConfidence: "Mixed: writing credits on major hits; production specifics often behind NDA."
  },
  {
    id: "PDNA-000039",
    name: "Shellback",
    regionScene: "Sweden pop",
    coreDnaAngle: "Modern pop punch, guitar/synth hybrid hooks",
    country: "Sweden",
    region: "Stockholm",
    primaryGenres: ["pop", "rock-pop", "electropop"],
    sceneMovement: "Max Martin lineage, modern pop punch",
    signatureSoundSummary: "Modern pop punch, guitar-synth hybrid hooks, and aggressive brightness.",
    artisticDna: "Shellback adds teeth to pop — distortion and punch without losing hook clarity.",
    technicalDna: "Verified Max Martin camp; audible analysis suggests distorted guitars, synth hooks, loud drums.",
    rhythmicDna: "Pop-rock hybrid grid, driving kick, snare authority.",
    melodicHarmonicDna: "Power-pop hooks, major-key energy, catchy intervals.",
    arrangementDna: "Impact chorus, guitar-synth layering, bridge dynamic drop.",
    typeBeatInspiredDirection:
      "Punchy pop with guitar-synth hybrid hooks. Avoid copying Shake It Off or Blank Space production.",
    originalityTwist: "Shellback punch on minimalist amapiano — one keyboard, maximum pop vocal engineering.",
    researchConfidence: "Mixed: credits on Taylor Swift era; per-track verification needed."
  },
  {
    id: "PDNA-000040",
    name: "Nile Rodgers",
    regionScene: "US disco/funk/pop",
    coreDnaAngle: "Guitar groove architecture, live-dance precision, elegant repetition",
    country: "United States",
    region: "New York",
    primaryGenres: ["disco", "funk", "pop", "R&B"],
    sceneMovement: "Chic, disco-funk, modern pop collaborator",
    signatureSoundSummary: "Chicken-scratch guitar, disco-funk groove, elegant repetition, and dancefloor precision.",
    artisticDna: "Rodgers makes guitar a rhythm section — strumming pattern is the song's DNA.",
    technicalDna: "Verified Fender Strat approach; audible analysis suggests tight disco rhythm guitar, punchy live drums, string pads.",
    rhythmicDna: "Disco pulse, guitar syncopation, four-on-the-floor foundation.",
    melodicHarmonicDna: "Minor disco hooks, funk chord movement, elegant simplicity.",
    arrangementDna: "Groove sustain, breakdown to bass/guitar, build back to full.",
    typeBeatInspiredDirection:
      "Disco-funk groove with rhythm guitar architecture. Avoid copying Le Freak or Get Lucky guitar patterns.",
    originalityTwist: "Rodgers guitar logic on highlife palm-muted patterns or amapiano bassline interplay.",
    researchConfidence: "Mixed: extensive credits; per-track guitar patterns D-tier for imitation risk."
  },
  {
    id: "PDNA-000041",
    name: "Trevor Horn",
    regionScene: "UK synthpop/new wave",
    coreDnaAngle: "Hyper-detailed pop production, studio maximalism, digital sheen",
    country: "United Kingdom",
    region: "London",
    primaryGenres: ["synthpop", "new wave", "pop", "prog"],
    sceneMovement: "ZTT Records, 80s studio maximalism",
    signatureSoundSummary: "Layered studio maximalism, digital sheen, punchy drums, and hyper-detailed pop.",
    artisticDna: "Horn treats pop as spectacle — every frequency filled with intention, drama in every layer.",
    technicalDna: "Verified Fairlight/sampler era; audible analysis suggests gated reverb drums, layered synths, vocal stacks.",
    rhythmicDna: "80s drum punch, gated snare, programmed precision.",
    melodicHarmonicDna: "Pop hook maximalism, orchestral stabs, prog complexity at times.",
    arrangementDna: "Dramatic intros, multi-section epics, collage dynamics.",
    typeBeatInspiredDirection:
      "Maximalist 80s-pop production with gated drums and layered synths. Avoid copying Owner of a Lonely Heart or Slave to the Rhythm.",
    originalityTwist: "Horn maximalism with only three sound sources — constraint-driven layering.",
    researchConfidence: "Mixed: production legend status; per-track layer details need citation."
  },
  {
    id: "PDNA-000042",
    name: "Flood",
    regionScene: "UK alternative/electronic rock",
    coreDnaAngle: "Industrial space, texture-forward rock, atmospheric mixing",
    country: "United Kingdom",
    region: "London",
    primaryGenres: ["alternative rock", "electronic", "industrial"],
    sceneMovement: "Nine Inch Nails, U2, Depeche Mode mixing/production",
    signatureSoundSummary: "Vast spatial mixes, texture-forward rock, industrial weight, and atmospheric depth.",
    artisticDna: "Flood sculpts space — guitars become weather systems, vocals float in designed air.",
    technicalDna: "Verified mixing/production credits; audible analysis suggests wide stereo, long reverbs, layered guitars.",
    rhythmicDna: "Rock/industrial pulse, electronic percussion blend.",
    melodicHarmonicDna: "Minor-key atmosphere, simple hooks in vast space.",
    arrangementDna: "Slow builds, dynamic explosions, texture crescendos.",
    typeBeatInspiredDirection:
      "Atmospheric rock-electronic with vast spatial mix. Avoid copying The Downward Spiral or Achtung Baby sonic fingerprints.",
    originalityTwist: "Flood spatial design on hip-hop vocal stacks — rap in cathedral space.",
    researchConfidence: "Mixed: credits extensive; mix chain specifics D-tier."
  },
  {
    id: "PDNA-000043",
    name: "Nigel Godrich",
    regionScene: "UK alternative rock",
    coreDnaAngle: "Intimate abstraction, band texture, emotional digital-era space",
    country: "United Kingdom",
    region: "London",
    primaryGenres: ["alternative rock", "electronic", "experimental"],
    sceneMovement: "Radiohead production, Atoms for Peace",
    signatureSoundSummary: "Intimate abstraction, experimental texture, Radiohead sonic world, and digital-age warmth.",
    artisticDna: "Godrich captures alienation beautifully — experimental choices serve emotional narrative.",
    technicalDna: "Verified Radiohead collaboration; audible analysis suggests modular synth, guitar texture, unconventional recording.",
    rhythmicDna: "Rock pulse to electronic glitch, tempo flexibility.",
    melodicHarmonicDna: "Modal ambiguity, unsettling beauty, Thom Yorke melodic contour.",
    arrangementDna: "Non-standard structures, fade to noise, silence as element.",
    typeBeatInspiredDirection:
      "Experimental rock-electronic texture with intimate abstraction. Avoid copying OK Computer or Kid A fingerprints.",
    originalityTwist: "Godrich abstraction on clean pop vocal — experimental processing of conventional song.",
    researchConfidence: "Mixed: Radiohead catalogue documented; technique specifics often D-tier."
  },
  {
    id: "PDNA-000044",
    name: "Steve Albini",
    regionScene: "US alternative rock",
    coreDnaAngle: "Raw room sound, anti-gloss recording, performance realism",
    country: "United States",
    region: "Chicago",
    primaryGenres: ["alternative rock", "punk", "noise rock", "indie"],
    sceneMovement: "Electrical Audio, 90s indie rock",
    signatureSoundSummary: "Live room capture, minimal overdub, anti-gloss philosophy, and performance realism.",
    artisticDna: "Albini documents truth — performance is the product, production should not lie.",
    technicalDna: "Verified analog recording philosophy; audible analysis suggests room mics, minimal compression, natural dynamics.",
    rhythmicDna: "Live drummer, band interplay, no grid correction.",
    melodicHarmonicDna: "Performance-first, no harmonic sweetening.",
    arrangementDna: "Documentary capture, song as performed.",
    typeBeatInspiredDirection:
      "Live-room capture aesthetic with minimal processing. Avoid copying In Utero or Surfa Rosa specific room sounds.",
    originalityTwist: "Albini realism on fully electronic session — live take discipline for programmed instruments.",
    researchConfidence: "Mixed: philosophy well-documented in interviews; per-session Tier A possible."
  },
  {
    id: "PDNA-000045",
    name: "Linda Perry",
    regionScene: "US pop/rock",
    coreDnaAngle: "Song-first emotional production, vocal-centered arrangements",
    country: "United States",
    region: "Los Angeles",
    primaryGenres: ["pop", "rock", "alternative"],
    sceneMovement: "4 Non Blondes, songwriter-producer era",
    signatureSoundSummary: "Song-first production, vocal-centered arrangements, and emotional directness.",
    artisticDna: "Perry leads with voice — production serves confessional emotional delivery.",
    technicalDna: "Verified songwriter-producer credits; audible analysis suggests piano-guitar foundation, vocal forward mix.",
    rhythmicDna: "Rock/pop mid-tempo, live feel, straightforward grids.",
    melodicHarmonicDna: "Emotional chord progressions, anthemic hooks.",
    arrangementDna: "Verse build to explosive chorus, vocal showcase.",
    typeBeatInspiredDirection:
      "Vocal-centered pop-rock with emotional directness. Avoid copying Beautiful or Get the Party Started arrangements.",
    originalityTwist: "Perry vocal-centrism on sparse trap beat — one vocal, one 808, emotional lyrics.",
    researchConfidence: "Mixed: writing credits clear; production role per-track needs verification."
  },
  {
    id: "PDNA-000046",
    name: "Tainy",
    regionScene: "Puerto Rico reggaeton/Latin pop",
    coreDnaAngle: "Futuristic reggaeton, sleek dembow evolution, melodic atmosphere",
    country: "Puerto Rico",
    region: "San Juan",
    primaryGenres: ["reggaeton", "Latin pop", "trap"],
    sceneMovement: "Modern reggaeton, Neo Records",
    signatureSoundSummary: "Sleek dembow, futuristic synths, melodic atmosphere, and pop-reggaeton fusion.",
    artisticDna: "Tainy evolves reggaeton forward — dembow stays root, everything else is future.",
    technicalDna: "Verified modern reggaeton production; audible analysis suggests clean dembow pattern, synth atmosphere, vocal production.",
    rhythmicDna: "Dembow bounce, trap hat influence, kick syncopation.",
    melodicHarmonicDna: "Minor atmospheric synths, hook melodies, Latin pop chord color.",
    arrangementDna: "Intro atmosphere, dembow drop, hook-centric.",
    typeBeatInspiredDirection:
      "Futuristic dembow with melodic atmosphere and clean production. Avoid copying Tainy's specific UN VERANO SÓLO synth motifs.",
    originalityTwist: "Tainy sleekness on amapiano piano or UK funky shuffle.",
    researchConfidence: "Mixed: modern credits traceable; per-track verification needed."
  },
  {
    id: "PDNA-000047",
    name: "Luny Tunes",
    regionScene: "Puerto Rico reggaeton",
    coreDnaAngle: "Classic dembow architecture, club-reggaeton foundations",
    country: "Puerto Rico",
    region: "San Juan",
    primaryGenres: ["reggaeton", "Latin urban"],
    sceneMovement: "Mas Flow, reggaeton golden era",
    signatureSoundSummary: "Classic dembow, club-ready energy, and foundational reggaeton architecture.",
    artisticDna: "Luny Tunes codify dembow — the pattern is religion, the club is church.",
    technicalDna: "Verified reggaeton production duo; audible analysis suggests dembow kick-hat pattern, synth stabs, vocal layering.",
    rhythmicDna: "Dembow three-three-two kick pattern, steady hats, perreo bounce.",
    melodicHarmonicDna: "Simple minor hooks, synth brass, catchy loops.",
    arrangementDna: "DJ-friendly intro, dembow sustain, hook repeat.",
    typeBeatInspiredDirection:
      "Classic dembow reggaeton with club energy. Avoid copying Mas Flow specific loops.",
    originalityTwist: "Luny dembow with West African afro-funk guitar or Indian dhol percussion.",
    researchConfidence: "Mixed: foundational reggaeton history; per-track credits need citation."
  },
  {
    id: "PDNA-000048",
    name: "Sarz",
    regionScene: "Nigeria Afrobeats",
    coreDnaAngle: "Clean rhythmic bounce, melodic restraint, Afropop polish",
    country: "Nigeria",
    region: "Lagos",
    primaryGenres: ["Afrobeats", "Afropop"],
    sceneMovement: "Nigerian Afrobeats production",
    signatureSoundSummary: "Clean percussion bounce, melodic restraint, Afropop polish, and dancefloor clarity.",
    artisticDna: "Sarz makes complexity feel easy — rhythm breathes, melody knows when to stop.",
    technicalDna: "Verified Afrobeats production; audible analysis suggests percussion layers, log drum elements, clean mix.",
    rhythmicDna: "Afrobeats bounce, percussion conversation, kick patterns for dance.",
    melodicHarmonicDna: "Simple earworm hooks, major-key optimism, occasional minor color.",
    arrangementDna: "Percussion intro, groove sustain, vocal hook focus.",
    typeBeatInspiredDirection:
      "Clean Afrobeats bounce with melodic restraint. Avoid copying Sarz's specific Wizkid/Burna collaborations.",
    originalityTwist: "Sarz bounce with Brazilian baile funk tamborzão or UK drill hats.",
    researchConfidence: "Mixed: credits on major Afrobeats hits; per-track verification needed."
  },
  {
    id: "PDNA-000049",
    name: "Kabza De Small",
    regionScene: "South Africa amapiano",
    coreDnaAngle: "Log-drum language, hypnotic piano loops, long-form groove",
    country: "South Africa",
    region: "Pretoria",
    primaryGenres: ["amapiano", "house", "Afrobeats"],
    sceneMovement: "Piano King, amapiano pioneer",
    signatureSoundSummary: "Log drum bounce, hypnotic piano loops, long-form groove, and township energy.",
    artisticDna: "Kabza makes piano hypnotic — loops are mantras, log drum is heartbeat.",
    technicalDna: "Verified amapiano production; audible analysis suggests log drum, piano riff loops, shaker percussion.",
    rhythmicDna: "Log drum pattern, house-influenced kick, shaker swing.",
    melodicHarmonicDna: "Simple piano loops, jazzy chord extensions, repetitive hypnosis.",
    arrangementDna: "Long groove sustain, DJ-friendly length, minimal breakdown.",
    typeBeatInspiredDirection:
      "Amapiano groove with log drum and hypnotic piano loop. Avoid copying Kabza's specific piano riffs.",
    originalityTwist: "Kabza groove with trap 808 sub or reggaeton dembow kick hybrid.",
    researchConfidence: "Mixed: amapiano pioneer status documented; per-track citations needed."
  },
  {
    id: "PDNA-000050",
    name: "DJ Rashad",
    regionScene: "Chicago footwork",
    coreDnaAngle: "Hyperkinetic sampling, battle rhythm, emotional repetition at high speed",
    country: "United States",
    region: "Chicago",
    primaryGenres: ["footwork", "juke", "electronic"],
    sceneMovement: "Teklife, Chicago footwork",
    signatureSoundSummary: "Hyperkinetic drums, vocal chop samples, battle energy, and emotional repetition at 160 BPM.",
    artisticDna: "Rashad makes speed emotional — footwork is battle music that cries and celebrates simultaneously.",
    technicalDna: "Verified footwork production; audible analysis suggests 160 BPM drum patterns, vocal sample chops, sub-bass.",
    rhythmicDna: "Syncopated kick/snare at high tempo, triplet fills, drum machine precision.",
    melodicHarmonicDna: "Sampled vocal hooks, soul/R&B fragments sped and chopped.",
    arrangementDna: "Short loops, battle structure, DJ mix logic.",
    typeBeatInspiredDirection:
      "Footwork tempo beat with hyperkinetic drums and vocal chop space. Avoid copying Rashad's specific Traxman-sample flips.",
    originalityTwist: "Rashad footwork speed on slow dembow half-time — rhythmic tension from tempo clash.",
    researchConfidence: "Mixed: Teklife history documented; per-track sample sources need citation."
  }
];
